import type {
  ConfluenceConfig,
  ParseConfluenceEntriesOptions,
  ParseConfluenceParseDebugChunk,
  ParseConfluenceParseDebugReport,
  ParseConfluenceParseDebugRow,
  ParseConfluenceParseDebugTable,
} from "@shared/types";
import { ConfluenceClient } from "./confluence/confluence-client";
import {
  generateXhtmlTable,
  generateSingleTable,
  normalizeAttachmentOrder,
} from "./confluence/table-formatter";
import { stripHtml } from "./utils";
import { logger } from "./logger";

function normalizeFilename(name: string): string {
  if (!name) return "";
  let decoded = name;
  
  decoded = decoded
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&nbsp;/g, " ");

  try {
    decoded = decodeURIComponent(decoded);
  } catch (e) {
    // ignore
  }

  return decoded.trim().toLowerCase();
}

function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&quot;/g, '"')
    .replace(/&#34;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

export class ConfluenceService {
  private readonly config: ConfluenceConfig;
  private readonly rawClient: ConfluenceClient;

  constructor(config: ConfluenceConfig) {
    this.config = config;
    this.rawClient = new ConfluenceClient(config);
  }

  async validateConnection(): Promise<string> {
    return this.rawClient.validateConnection();
  }

  async getPage(pageId: string) {
    return this.rawClient.getPage(pageId);
  }

  async getPagePreview(pageId: string): Promise<{ title: string; content: string; version: number }> {
    const page = await this.getPage(pageId);
    return {
      title: page.title,
      content: page.body?.storage?.value || "",
      version: page.version?.number || 1,
    };
  }

  async uploadAttachment(pageId: string, filename: string, base64Data: string) {
    return this.rawClient.uploadAttachment(pageId, filename, base64Data);
  }

  async updatePage(pageId: string, title: string, content: string, version: number) {
    return this.rawClient.updatePage(pageId, title, content, version);
  }

  generateXhtmlTable(entries: any[], jiraBaseUrl?: string, jiraServerId?: string) {
    return generateXhtmlTable(entries, jiraBaseUrl, jiraServerId);
  }

  private stripGeneratedMarkers(content: string): string {
    return content.replace(
      /\s*<p>\s*Generated by QA Buddy\s*[-—]\s*[^<]+<\/p>\s*/gi,
      "\n"
    );
  }

  private normalizeTableSpacing(content: string): string {
    return content
      .replace(/(?:\s*<p>\s*(?:<br\s*\/?>|\u00a0|&nbsp;)?\s*<\/p>\s*){2,}/gi, "\n<p><br /></p>\n")
      .replace(/(<\/table>)\s*(?:<p>\s*(?:<br\s*\/?>|\u00a0|&nbsp;)?\s*<\/p>\s*)+(?=<table\b)/gi, "$1\n<p><br /></p>\n")
      .replace(/^\s+|\s+$/g, "");
  }

  private collectParsedTables(content: string): Array<{ qaIndex: number; html: string; start: number; end: number; entry: any }> {
    const tables: Array<{ qaIndex: number; html: string; start: number; end: number; entry: any }> = [];
    const tableRegex = /<table[^>]*>[\s\S]*?<\/table>/gi;
    let tableMatch;
    let qaIndex = 0;

    while ((tableMatch = tableRegex.exec(content)) !== null) {
      const html = tableMatch[0];
      const parsed = this.parseSingleTable(html, false);
      if (parsed.entry && parsed.entry.testCaseNo) {
        tables.push({
          qaIndex,
          html,
          start: tableMatch.index,
          end: tableMatch.index + html.length,
          entry: parsed.entry,
        });
        qaIndex++;
      }
    }

    return tables;
  }

  private mergeEntriesIntoContent(
    content: string,
    entries: any[],
    jiraBaseUrl?: string,
    jiraServerId?: string,
    deletedTableIndices: number[] = []
  ): { content: string; replacedCount: number; appendedCount: number; deletedCount: number } {
    const sanitizedContent = this.normalizeTableSpacing(this.stripGeneratedMarkers(content));
    const parsedTables = this.collectParsedTables(sanitizedContent);
    const replacements = new Map<number, string>();
    const appendedTables: string[] = [];
    const deletedSet = new Set(deletedTableIndices);

    for (const entry of entries) {
      const tableHtml = generateSingleTable(entry, jiraBaseUrl, jiraServerId);
      if (typeof entry.sourceTableIndex === "number") {
        replacements.set(entry.sourceTableIndex, tableHtml);
      } else {
        appendedTables.push(tableHtml);
      }
    }

    if (replacements.size === 0 && appendedTables.length === 0 && deletedSet.size === 0) {
      return { content: sanitizedContent, replacedCount: 0, appendedCount: 0, deletedCount: 0 };
    }

    let nextContent = sanitizedContent;
    const targets = parsedTables
      .filter((table) => replacements.has(table.qaIndex) || deletedSet.has(table.qaIndex))
      .sort((a, b) => b.start - a.start);

    for (const table of targets) {
      if (deletedSet.has(table.qaIndex)) {
        const trailingBreakMatch = nextContent.slice(table.end).match(/^\s*<p><br\s*\/?><\/p>/i);
        const removeUntil = trailingBreakMatch ? table.end + trailingBreakMatch[0].length : table.end;
        nextContent = nextContent.slice(0, table.start) + nextContent.slice(removeUntil);
        continue;
      }
      nextContent =
        nextContent.slice(0, table.start) +
        replacements.get(table.qaIndex)! +
        nextContent.slice(table.end);
    }

    if (appendedTables.length > 0) {
      const appendedHtml = this.normalizeTableSpacing(appendedTables.join("\n<p><br /></p>\n"));
      nextContent = nextContent.trim() ? `${nextContent}\n<p><br /></p>\n${appendedHtml}` : appendedHtml;
    }

    nextContent = this.normalizeTableSpacing(nextContent);

    return {
      content: nextContent,
      replacedCount: targets.filter((table) => replacements.has(table.qaIndex)).length,
      appendedCount: appendedTables.length,
      deletedCount: targets.filter((table) => deletedSet.has(table.qaIndex)).length,
    };
  }

  async syncToConfluence(
    pageId: string,
    entries: any[],
    jiraBaseUrl?: string,
    jiraServerId?: string,
    deletedTableIndices: number[] = []
  ): Promise<{ pageTitle: string; pageUrl: string; entryCount: number; imageCount: number; attachmentCount: number }> {
    const page = await this.getPage(pageId);
    const currentVersion = page.version?.number || 1;
    const content = page.body?.storage?.value || "";

    const finalJiraServerId = jiraServerId || await this.resolveJiraServerId(content);

    let existingAttachmentNames: string[] = [];
    try {
      const attachments = await this.rawClient.getAttachments(pageId);
      existingAttachmentNames = attachments.map((att: any) => normalizeFilename(att.title));
    } catch (attErr) {
      logger.error("Confluence", "Failed to fetch existing attachments during sync:", attErr);
    }

    let imageCount = 0;
    let attachmentCount = 0;
    for (const entry of entries) {
      for (const img of normalizeAttachmentOrder(entry.images || [])) {
        if (!img.data) continue;

        const normalizedImgName = normalizeFilename(img.name);
        if (existingAttachmentNames.includes(normalizedImgName)) {
          continue;
        }

        try {
          await this.uploadAttachment(pageId, img.name, img.data);
          if (img.data.startsWith("data:image/")) {
            imageCount++;
          } else {
            attachmentCount++;
          }
        } catch (uploadErr) {
          logger.error("Confluence", `Failed to upload attachment ${img.name}:`, uploadErr);
          throw uploadErr;
        }
      }
    }

    const { content: bodyHtml, replacedCount, appendedCount, deletedCount } = this.mergeEntriesIntoContent(
      content,
      entries,
      jiraBaseUrl,
      finalJiraServerId,
      deletedTableIndices
    );

    const updated = await this.updatePage(pageId, page.title, bodyHtml, currentVersion);

    return {
      pageTitle: updated.title,
      pageUrl: `${this.config.baseUrl.replace(/\/+$/, "")}/spaces/${page.space?.key || ""}/pages/${pageId}`,
      entryCount: replacedCount + appendedCount + deletedCount,
      imageCount,
      attachmentCount,
    };
  }

  async previewSyncXhtml(
    pageId: string,
    entries: any[],
    jiraBaseUrl?: string,
    jiraServerId?: string
  ): Promise<{ currentTitle: string; currentVersion: number; generatedTables: string; entryCount: number; existingEntryCount: number }> {
    const page = await this.getPage(pageId);
    const currentVersion = page.version?.number || 1;
    const content = page.body?.storage?.value || "";

    const existingEntries = this.parseEntriesFromContent(content);
    const finalJiraServerId = jiraServerId || await this.resolveJiraServerId(content);
    const generatedTables = this.generateXhtmlTable(entries, jiraBaseUrl, finalJiraServerId);

    return {
      currentTitle: page.title,
      currentVersion,
      generatedTables,
      entryCount: entries.length,
      existingEntryCount: existingEntries.length,
    };
  }

  async getPageByUrl(url: string) {
    const pageIdMatch = url.match(/pages\/(\d+)/) || url.match(/pageId=(\d+)/);
    const pageId = pageIdMatch ? pageIdMatch[1] : "";
    if (pageId) {
      return this.getPage(pageId);
    }
    throw new Error("Invalid Confluence URL. Could not find page ID.");
  }

  async summarize(prompt: string, ollama?: any) {
    return {
      answer: "Fitur pencarian global Confluence belum diimplementasi. Mohon berikan URL spesifik halaman Confluence.",
      pages: []
    };
  }

  async getAttachments(pageId: string): Promise<any[]> {
    return this.rawClient.getAttachments(pageId);
  }

  async downloadAttachment(downloadUrl: string): Promise<Buffer> {
    return this.rawClient.downloadAttachment(downloadUrl);
  }

  async extractTestCases(url: string, depth: string, ollama?: any, ragContext?: string, ocrText?: string) {
    const page = await this.getPageByUrl(url);
    const content = page.body?.storage?.value || "";
    
    let testCases: any[] = [];
    if (ollama && typeof ollama.extractTestCases === "function") {
      const extracted = await ollama.extractTestCases(stripHtml(content), depth as any, ragContext, ocrText);
      if (extracted && extracted.length > 0) {
        testCases = extracted;
      }
    }
    
    return {
      testCases,
      pageTitle: page.title,
      sourceUrl: url
    };
  }

  private async resolveJiraServerId(content: string): Promise<string | undefined> {
    const fromContent = this.detectJiraServerId(content);
    if (fromContent) {
      return fromContent;
    }
    return this.rawClient.detectJiraServerIdFromAppLinks();
  }

  detectJiraServerId(content: string): string | undefined {
    const normalized = decodeHtmlEntities(content);
    const patterns = [
      /<ac:parameter\b[^>]*ac:name=["']serverId["'][^>]*>\s*([^<]+?)\s*<\/ac:parameter>/i,
      /<ri:server\b[^>]*ri:server-id=["']([^"']+)["'][^>]*\/?>/i,
      /\bdata-jira-server-id=["']([^"']+)["']/i,
      /\bdata-server-id=["']([^"']+)["']/i,
      /\bserver-id=["']([^"']+)["']/i,
      /["']serverId["']\s*[:=]\s*["']([^"']+)["']/i,
      /\bserverId=["']([^"']+)["']/i,
      /\bserverId=([A-Za-z0-9:._-]+)/i,
    ];

    for (const pattern of patterns) {
      const match = normalized.match(pattern);
      if (match?.[1]?.trim()) {
        return match[1].trim();
      }
    }

    return undefined;
  }

  parseEntriesFromContent(content: string): any[] {
    return this.collectParsedTables(content).map((table) => ({
      ...table.entry,
      sourceTableIndex: table.qaIndex,
      sourceTableHtml: table.html,
      isDirty: false,
    }));
  }

  async parseEntriesFromPage(pageId: string, options?: ParseConfluenceEntriesOptions): Promise<{
    pageId: string;
    pageTitle: string;
    contentLoaded: boolean;
    entries: any[];
    jiraServerId?: string;
    error?: string;
    debug?: ParseConfluenceParseDebugReport;
  }> {
    try {
      const page = await this.getPage(pageId);
      const content = page.body?.storage?.value || "";
      const parsed = options?.debug ? this.collectParsedTablesWithDebug(content) : { tables: this.collectParsedTables(content) };
      const entries = parsed.tables.map((table) => ({
        ...table.entry,
        sourceTableIndex: table.qaIndex,
        sourceTableHtml: table.html,
        isDirty: false,
      }));

      const viewContent = page.body?.view?.value || "";
      if (viewContent && entries.length > 0) {
        this.enrichEntriesFromView(entries, viewContent);
      }

      const jiraServerId = await this.resolveJiraServerId(content);

      try {
        const attachments = await this.rawClient.getAttachments(pageId);
        for (const entry of entries) {
          for (const img of entry.images) {
            const normalizedImgName = normalizeFilename(img.name);
            const matchedAtt = attachments.find((att: any) => {
              const normalizedAttTitle = normalizeFilename(att.title);
              return normalizedAttTitle === normalizedImgName;
            });

            if (matchedAtt && matchedAtt._links?.download) {
              try {
                const buffer = await this.rawClient.downloadAttachment(matchedAtt._links.download);
                const base64 = buffer.toString("base64");
                const mimeType = matchedAtt.metadata?.mediaType || matchedAtt.mediaType || "image/png";
                img.data = `data:${mimeType};base64,${base64}`;
              } catch (downloadErr) {
                logger.error("Confluence", `Failed to download attachment ${img.name}:`, downloadErr);
              }
            }
          }
        }
      } catch (attErr) {
        logger.error("Confluence", "Failed to fetch attachments list for page:", attErr);
      }

      return {
        pageId,
        pageTitle: page.title || "",
        contentLoaded: true,
        entries,
        jiraServerId,
        debug: parsed.debug
          ? {
              ...parsed.debug,
              pageId,
              pageTitle: page.title || "",
            }
          : undefined,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      logger.error("Confluence", `Failed to fetch page content for ${pageId}:`, error);
      return {
        pageId,
        pageTitle: "",
        contentLoaded: false,
        entries: [],
        error: message,
        debug: options?.debug
          ? {
              pageId,
              pageTitle: "",
              rawPageContent: "",
              contentLength: 0,
              tableCount: 0,
              parsedTableCount: 0,
              skippedTableCount: 0,
              unmatchedHtmlChunks: [],
              tables: [],
            }
          : undefined,
      };
    }
  }

  private parseSingleTable(tableHtml: string, debug = false): { entry: any; debug?: ParseConfluenceParseDebugTable } {
    const entry: any = {
      id: "",
      testCaseNo: "",
      functionName: "",
      scenario: "",
      category: "Positive",
      inputData: "",
      steps: "",
      expectedResult: "",
      result: "PASS",
      images: [] as { id: string; name: string; data: string; order: number; note?: string }[],
    };
    const debugTable: ParseConfluenceParseDebugTable | undefined = debug
      ? {
          index: 0,
          parsed: false,
          rawHtml: tableHtml,
          rows: [],
          mappedFields: [],
        }
      : undefined;
    const recordRow = (row: ParseConfluenceParseDebugRow) => {
      debugTable?.rows.push(row);
    };

    const rowRegex = /<tr\b[^>]*>[\s\S]*?<\/tr>/gi;
    let rowMatch;

    while ((rowMatch = rowRegex.exec(tableHtml)) !== null) {
      const rowHtml = rowMatch[0];
      const labelMatch = rowHtml.match(/<td[^>]*>[\s\S]*?<strong>(.*?)<\/strong>[\s\S]*?<\/td>/i);
      if (!labelMatch) {
        recordRow({
          label: null,
          status: "missing-label",
          reason: "Row tidak memiliki label <strong> yang bisa dipetakan",
          rawHtml: rowHtml,
        });
        continue;
      }

      const label = labelMatch[1].trim();

      const tdRegex = /<td[^>]*>([\s\S]*?)<\/td>/gi;
      const tds: string[] = [];
      let tdMatch;
      while ((tdMatch = tdRegex.exec(rowHtml)) !== null) {
        tds.push(tdMatch[1].trim());
      }
      if (tds.length < 2) {
        recordRow({
          label,
          status: "empty-value",
          reason: "Row memiliki label, tetapi value cell tidak lengkap",
          rawHtml: rowHtml,
        });
        continue;
      }
      const value = tds[1];
      const valuePreview = stripHtml(this.cleanConfluenceMacros(value)).replace(/\s+/g, " ").trim().slice(0, 240);

      switch (label) {
        case "No. Test Case":
          entry.testCaseNo = this.extractTextValue(value);
          debugTable?.mappedFields.push("testCaseNo");
          recordRow({ label, status: "mapped", mappedField: "testCaseNo", rawHtml: rowHtml, valuePreview });
          break;
        case "Function":
          entry.functionName = this.extractTextValue(value);
          debugTable?.mappedFields.push("functionName");
          recordRow({ label, status: "mapped", mappedField: "functionName", rawHtml: rowHtml, valuePreview });
          break;
        case "Scenario":
          entry.scenario = this.extractTextValue(value);
          debugTable?.mappedFields.push("scenario");
          recordRow({ label, status: "mapped", mappedField: "scenario", rawHtml: rowHtml, valuePreview });
          break;
        case "Kategori":
          entry.category = this.extractTextValue(value);
          debugTable?.mappedFields.push("category");
          recordRow({ label, status: "mapped", mappedField: "category", rawHtml: rowHtml, valuePreview });
          break;
        case "Input Data":
          entry.inputData = this.extractTextLines(value);
          debugTable?.mappedFields.push("inputData");
          recordRow({ label, status: "mapped", mappedField: "inputData", rawHtml: rowHtml, valuePreview });
          break;
        case "Steps":
          entry.steps = this.extractTextLines(value);
          debugTable?.mappedFields.push("steps");
          recordRow({ label, status: "mapped", mappedField: "steps", rawHtml: rowHtml, valuePreview });
          break;
        case "Expected Result":
          entry.expectedResult = this.extractTextLines(value);
          debugTable?.mappedFields.push("expectedResult");
          recordRow({ label, status: "mapped", mappedField: "expectedResult", rawHtml: rowHtml, valuePreview });
          break;
        case "Result":
          entry.result = this.extractResult(value);
          debugTable?.mappedFields.push("result");
          recordRow({ label, status: "mapped", mappedField: "result", rawHtml: rowHtml, valuePreview });
          break;
        case "Screen Capture": {
          const orderedAttachmentBlocks = value.match(/<li\b[^>]*data-qa-attachment-order=["'][^"']+["'][^>]*>[\s\S]*?<\/li>/gi) || [];
          if (orderedAttachmentBlocks.length > 0) {
            let attachmentIndex = 0;
            for (const block of orderedAttachmentBlocks) {
              attachmentIndex++;
              const orderMatch = block.match(/data-qa-attachment-order=["'](\d+)["']/i);
              const noteMatch = block.match(/data-qa-attachment-note=["']([^"']*)["']/i);
              const nameMatch =
                block.match(/ri:filename="([^"]+)"/i) ||
                block.match(/data-linked-resource-default-alias="([^"]+)"/i) ||
                block.match(/data-file-src="[^"]*\/([^"\/]+)"/i) ||
                block.match(/data-qa-attachment-name=["']([^"']+)["']/i);
              const name = nameMatch?.[1];
              if (name) {
                entry.images.push({
                  id: `${name}::${attachmentIndex}`,
                  name,
                  data: "",
                  order: orderMatch ? Number(orderMatch[1]) : attachmentIndex,
                  note: noteMatch ? decodeHtmlEntities(noteMatch[1]) : "",
                });
              }
            }
            debugTable?.mappedFields.push("images");
            recordRow({
              label,
              status: "mapped",
              mappedField: "images",
              rawHtml: rowHtml,
              valuePreview,
            });
            break;
          }

          const blockRegex = /<li\b[^>]*>[\s\S]*?<\/li>|<p\b[^>]*>[\s\S]*?<\/p>/gi;
          const blocks = value.match(blockRegex) || [];
          let attachmentIndex = 0;
          let pendingNote = "";
          for (const block of blocks) {
            const nameMatch =
              block.match(/ri:filename="([^"]+)"/i) ||
              block.match(/data-linked-resource-default-alias="([^"]+)"/i) ||
              block.match(/data-file-src="[^"]*\/([^"\/]+)"/i);
            if (nameMatch) {
              attachmentIndex++;
              const name = nameMatch[1];
              entry.images.push({
                id: `${name}::${attachmentIndex}`,
                name,
                data: "",
                order: attachmentIndex,
                note: pendingNote,
              });
              pendingNote = "";
              continue;
            }

            const text = this.extractTextValue(block).trim();
            if (text && text !== "-" && text !== "Click here to expand...") {
              pendingNote = pendingNote ? `${pendingNote}\n${text}` : text;
            }
          }
          debugTable?.mappedFields.push("images");
          recordRow({
            label,
            status: "mapped",
            mappedField: "images",
            rawHtml: rowHtml,
            reason: blocks.length === 0 ? "Screen Capture kosong" : "Screen Capture dipetakan tanpa marker attachment eksplisit",
            valuePreview,
          });
          break;
        }
        default:
          recordRow({
            label,
            status: "unmapped-label",
            reason: "Label tidak dikenali oleh parser",
            rawHtml: rowHtml,
            valuePreview,
          });
          break;
      }
    }

    if (debugTable) {
      debugTable.parsed = Boolean(entry.testCaseNo);
      debugTable.reason = entry.testCaseNo ? undefined : "No. Test Case tidak ditemukan";
      debugTable.entrySummary = {
        testCaseNo: entry.testCaseNo,
        functionName: entry.functionName,
        scenario: entry.scenario,
        category: entry.category,
        result: entry.result,
        imageCount: entry.images.length,
      };
    }

    return { entry, debug: debugTable };
  }

  private collectParsedTablesWithDebug(content: string): {
    tables: Array<{ qaIndex: number; html: string; start: number; end: number; entry: any }>;
    debug?: ParseConfluenceParseDebugReport;
  } {
    const tables: Array<{ qaIndex: number; html: string; start: number; end: number; entry: any }> = [];
    const debugTables: ParseConfluenceParseDebugTable[] = [];
    const unmatchedHtmlChunks: ParseConfluenceParseDebugChunk[] = [];
    const tableRegex = /<table[^>]*>[\s\S]*?<\/table>/gi;
    let tableMatch;
    let qaIndex = 0;
    let tableIndex = 0;
    let lastEnd = 0;

    while ((tableMatch = tableRegex.exec(content)) !== null) {
      const html = tableMatch[0];
      const gap = content.slice(lastEnd, tableMatch.index).trim();
      if (gap) {
        unmatchedHtmlChunks.push({
          index: unmatchedHtmlChunks.length,
          reason: "HTML di luar tabel tidak diproses parser",
          rawHtml: gap,
        });
      }

      const parsed = this.parseSingleTable(html, true);
      const entry = parsed.entry;
      const debugTable = parsed.debug;
      const isParsed = Boolean(entry && entry.testCaseNo);

      if (debugTable) {
        debugTable.index = tableIndex;
        debugTable.parsed = isParsed;
        debugTable.reason = isParsed ? undefined : "No. Test Case tidak ditemukan";
        debugTables.push(debugTable);
      }

      if (isParsed) {
        tables.push({
          qaIndex,
          html,
          start: tableMatch.index,
          end: tableMatch.index + html.length,
          entry,
        });
        qaIndex++;
      }

      lastEnd = tableMatch.index + html.length;
      tableIndex++;
    }

    const tail = content.slice(lastEnd).trim();
    if (tail) {
      unmatchedHtmlChunks.push({
        index: unmatchedHtmlChunks.length,
        reason: "HTML setelah tabel terakhir tidak diproses parser",
        rawHtml: tail,
      });
    }

    if (debugTables.length === 0 && unmatchedHtmlChunks.length === 0) {
      return { tables };
    }

    return {
      tables,
      debug: {
        pageId: "",
        rawPageContent: content,
        contentLength: content.length,
        tableCount: debugTables.length,
        parsedTableCount: tables.length,
        skippedTableCount: debugTables.filter((table) => !table.parsed).length,
        unmatchedHtmlChunks,
        tables: debugTables,
      },
    };
  }

  private enrichEntriesFromView(entries: any[], viewContent: string): void {
    const tableRegex = /<table[^>]*>[\s\S]*?<\/table>/gi;
    const viewTables: string[] = [];
    let tableMatch;
    while ((tableMatch = tableRegex.exec(viewContent)) !== null) {
      viewTables.push(tableMatch[0]);
    }

    let viewIndex = 0;
    for (const entry of entries) {
      while (viewIndex < viewTables.length) {
        const enriched = this.tryEnrichEntryScenarioFromViewTable(entry, viewTables[viewIndex]);
        viewIndex++;
        if (enriched) break;
      }
    }
  }

  private tryEnrichEntryScenarioFromViewTable(entry: any, viewTableHtml: string): boolean {
    const rowRegex = /<tr\b[^>]*>[\s\S]*?<\/tr>/gi;
    let rowMatch;

    while ((rowMatch = rowRegex.exec(viewTableHtml)) !== null) {
      const rowHtml = rowMatch[0];
      const labelMatch = rowHtml.match(/<td[^>]*>[\s\S]*?<strong>(.*?)<\/strong>[\s\S]*?<\/td>/i);
      if (!labelMatch) continue;

      if (labelMatch[1].trim() !== "Scenario") continue;

      const tdRegex = /<td[^>]*>([\s\S]*?)<\/td>/gi;
      const tds: string[] = [];
      let tdMatch;
      while ((tdMatch = tdRegex.exec(rowHtml)) !== null) {
        tds.push(tdMatch[1].trim());
      }

      if (tds.length >= 2) {
        const cellHtml = tds[1];
        const jiraKeyMatch = cellHtml.match(/data-jira-key=["']([^"']+)["']/i);
        const issueKey = jiraKeyMatch?.[1]?.trim();

        if (issueKey) {
          const summaryMatch = cellHtml.match(
            /<span\s+class\s*=\s*["'][^"']*\bsummary\b[^"']*["'][^>]*>([\s\S]*?)<\/span>/i
          );
          const summary = summaryMatch ? stripHtml(summaryMatch[1]).trim() : "";

          if (summary && !/Getting issue details/i.test(summary)) {
            entry.scenario = summary;
          } else {
            entry.scenario = issueKey;
          }
          entry.scenarioIssueKey = issueKey;
          entry.scenarioSummary = summary && !/Getting issue details/i.test(summary) ? summary : "";
          return true;
        }
      }

      break;
    }

    return false;
  }

  private cleanJiraMacro(macroHtml: string): string {
    const params: string[] = [];
    const paramRegex = /<ac:parameter ac:name=["']([^"']+)["']>([\s\S]*?)<\/ac:parameter>/gi;
    let match;
    while ((match = paramRegex.exec(macroHtml)) !== null) {
      const name = match[1].toLowerCase();
      if (name === "key" || name === "issuekey") {
        let value = match[2].trim();
        const riValue = value.match(/ri:value=["']([^"']+)["']/i);
        if (riValue) value = riValue[1];
        params.push(value);
      }
    }
    if (params.length > 0) return params.join(", ");
    const keyFallback = macroHtml.match(/([A-Z]{2,}-\d+)/);
    return keyFallback ? keyFallback[1] : "";
  }

  private cleanConfluenceMacros(html: string): string {
    let result = html;

    result = result.replace(
      /<ac:structured-macro[\s\S]*?ac:name=["']jira[\s\S]*?<\/ac:structured-macro>/gi,
      (match) => this.cleanJiraMacro(match)
    );

    result = result.replace(
      /<span[^>]*data-jira-key=["']([^"']+)["'][^>]*>[\s\S]*?<\/span>/gi,
      "$1"
    );

    result = result.replace(
      /<span[^>]*class=["'][^"']*\bjira-issue\b[^"']*["'][^>]*>[\s\S]*?<\/span>/gi,
      (match) => {
        const keyMatch = match.match(/([A-Z]{2,}-\d{1,9})/);
        return keyMatch ? keyMatch[1] : "";
      }
    );

    result = result.replace(
      /<ac:plain-text-link-body>\s*(?:<!\[CDATA\[)?([^\]<]+)(?:\]\]>)?\s*<\/ac:plain-text-link-body>/gi,
      "$1"
    );

    result = result.replace(/-\s*Getting issue details\.\.\./gi, "");
    result = result.replace(/\bGetting issue details\.\.\.\s*/gi, "");

    return result;
  }

  private extractTextValue(value: string): string {
    return stripHtml(this.cleanConfluenceMacros(value)).trim();
  }

  private extractTextLines(value: string): string {
    const cleaned = this.cleanConfluenceMacros(value);
    const liRegex = /<li\b[^>]*>([\s\S]*?)<\/li>/gi;
    const liItems: string[] = [];
    let match;
    while ((match = liRegex.exec(cleaned)) !== null) {
      liItems.push(stripHtml(match[1]).trim());
    }
    if (liItems.length > 0) {
      return liItems.join("\n");
    }

    const pRegex = /<p[^>]*>([\s\S]*?)<\/p>/gi;
    const pItems: string[] = [];
    while ((match = pRegex.exec(cleaned)) !== null) {
      const text = stripHtml(match[1]).trim();
      if (text) {
        pItems.push(text);
      }
    }
    if (pItems.length > 0) {
      return pItems.join("\n");
    }

    const brItems = cleaned.split(/<br\s*\/?>/i).map((s) => stripHtml(s).trim()).filter(Boolean);
    if (brItems.length > 1) {
      return brItems.join("\n");
    }

    return this.extractTextValue(cleaned);
  }

  private extractResult(value: string): string {
    const text = stripHtml(value).toLowerCase();

    const passPos = text.indexOf("pass");
    const failPos = text.indexOf("fail");
    const passedPos = text.indexOf("passed");
    const failedPos = text.indexOf("failed");

    if (passedPos !== -1 && failedPos !== -1) {
      return passedPos < failedPos ? "PASS" : "FAILED";
    }
    if (passPos !== -1 && failPos !== -1) {
      return passPos < failPos ? "PASS" : "FAILED";
    }
    if (passedPos !== -1 || (passPos !== -1 && failPos === -1)) {
      return "PASS";
    }
    if (failedPos !== -1 || failPos !== -1) {
      return "FAILED";
    }

    return "PASS";
  }
}
