//! Confluence service — held in app state. P3 wires connection testing + page
//! access; this module (P5b) adds page preview, attachment upload, page update,
//! Jira server-id detection, table generation, and Confluence-entry parsing.
//!
//! The HTML storage-format manipulation (XHTML tables, TOC macros, generated
//! markers) mirrors the Electron `confluence-service.ts` + `table-formatter.ts`
//! behaviour, ported to Rust regex.

use serde_json::Value;

use crate::models::app_config::ConfluenceConfig;
use crate::models::jira::ConfluenceTestImportEntry;
use crate::models::misc::{
    ConfluencePreviewResult, ParseConfluenceEntriesOptions, ParseConfluenceEntriesResult,
    SyncToConfluencePayload, SyncToConfluenceResult,
};
use crate::services::confluence::client::ConfluenceClient;
use crate::services::error::Result;
use crate::services::http::normalize_url;

pub struct ConfluenceService;

impl ConfluenceService {
    pub fn new() -> Self {
        Self
    }

    fn client(&self, config: &ConfluenceConfig) -> ConfluenceClient {
        ConfluenceClient::new(config)
    }

    /// Probe Confluence connectivity; returns a status string.
    pub async fn test_connection(&self, config: &ConfluenceConfig) -> Result<String> {
        self.client(config).validate_connection().await
    }

    /// Fetch a raw Confluence page document.
    pub async fn get_page(&self, config: &ConfluenceConfig, page_id: &str) -> Result<Value> {
        self.client(config).get_page(page_id).await
    }

    /// Resolve a user-facing Confluence URL to a page document.
    pub async fn get_page_by_url(&self, config: &ConfluenceConfig, url: &str) -> Result<Value> {
        self.client(config).get_page_by_url(url).await
    }

    /// List pages for a space key or ancestor/page id. Used by RAG indexing.
    pub async fn list_pages(&self, config: &ConfluenceConfig, space_or_page_id: &str) -> Result<Vec<Value>> {
        self.client(config).list_pages(space_or_page_id).await
    }

    pub async fn get_attachments(&self, config: &ConfluenceConfig, page_id: &str) -> Result<Vec<Value>> {
        self.client(config).get_attachments(page_id).await
    }

    pub async fn download_attachment(&self, config: &ConfluenceConfig, download_path: &str) -> Result<Vec<u8>> {
        self.client(config).download_attachment(download_path).await
    }

    /// Lightweight page preview: title, storage body, version.
    pub async fn get_page_preview(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
    ) -> Result<(String, String, u32)> {
        let page = self.get_page(config, page_id).await?;
        let title = page["title"].as_str().unwrap_or("").to_string();
        let content = page["body"]["storage"]["value"]
            .as_str()
            .unwrap_or("")
            .to_string();
        let version = page["version"]["number"].as_u64().unwrap_or(1) as u32;
        Ok((title, content, version))
    }

    /// Resolve the Jira application-link server id from Confluence applinks.
    pub async fn detect_jira_server_id(&self, config: &ConfluenceConfig) -> Result<Option<String>> {
        Ok(self.client(config).detect_jira_server_id().await)
    }

    pub async fn upload_attachment(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        filename: &str,
        data: Vec<u8>,
    ) -> Result<Value> {
        self.client(config)
            .upload_attachment(page_id, filename, data)
            .await
    }

    pub async fn update_page(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        title: &str,
        content: &str,
        version: u32,
    ) -> Result<Value> {
        self.client(config)
            .update_page(page_id, title, content, version)
            .await
    }

    // ── Storage-format helpers ──────────────────────────────────────────

    /// Strip previously-generated TOC macros, "Generated by QA Buddy" markers
    /// and any `<h1>` (Confluence rewrites these into the page title region).
    fn strip_generated_markers(content: &str) -> String {
        let gen = regex::Regex::new(
            r#"(?i)\s*<p>\s*Generated by QA Buddy\s*[-—]\s*[^<]+</p>\s*"#,
        )
        .unwrap();
        let toc_div = regex::Regex::new(
            r#"(?i)<div\b[^>]*\bdata-macro-name\s*=\s*"toc"[^>]*>[\s\S]*?</div>\s*"#,
        )
        .unwrap();
        let toc_macro = regex::Regex::new(
            r#"(?i)<ac:structured-macro\b[^>]*\bac:name\s*=\s*"toc"[^>]*>[\s\S]*?</ac:structured-macro>\s*"#,
        )
        .unwrap();
        let h1 = regex::Regex::new(r"(?i)<h1\b[^>]*>[\s\S]*?</h1>\s*").unwrap();

        let mut out = gen.replace_all(content, "\n").to_string();
        out = toc_div.replace_all(&out, "").to_string();
        out = toc_macro.replace_all(&out, "").to_string();
        out = h1.replace_all(&out, "").to_string();
        out
    }

    /// Generate a single XHTML `<table>` from import entries (one row each).
    /// Columns: TestCase No | Function Name | Scenario | Steps | Expected Result.
    pub fn generate_single_table(entries: &[ConfluenceTestImportEntry]) -> String {
        let mut html = String::from(
            "<table class=\"wrapped confluenceTable\"><colgroup><col/><col/><col/><col/><col/></colgroup>",
        );
        html.push_str("<tbody>");
        html.push_str(
            "<tr><th class=\"confluenceTh\">TestCase No</th><th class=\"confluenceTh\">Function Name</th><th class=\"confluenceTh\">Scenario</th><th class=\"confluenceTh\">Steps</th><th class=\"confluenceTh\">Expected Result</th></tr>",
        );
        for entry in entries {
            html.push_str(&format!(
                "<tr><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td></tr>",
                escape_html(&entry.test_case_no),
                escape_html(&entry.function_name),
                escape_html(&entry.scenario),
                escape_html(&entry.steps),
                escape_html(&entry.expected_result),
            ));
        }
        html.push_str("</tbody></table>");
        html
    }

    /// Count how many existing import-row tables already exist in the content
    /// (heuristic: tables with the QA Buddy column header).
    fn count_existing_entries(content: &str) -> usize {
        let re = regex::Regex::new(r"(?i)<tr>\s*<th[^>]*>\s*TestCase No").unwrap();
        re.find_iter(content).count()
    }

    // ── High-level operations ───────────────────────────────────────────

    /// Build a preview of the sync: current title/version, generated tables,
    /// and entry/existing-entry counts. Does not write to Confluence.
    pub async fn preview_sync(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        entries: &[Value],
    ) -> Result<ConfluencePreviewResult> {
        let (title, content, version) = self.get_page_preview(config, page_id).await?;
        let import_entries: Vec<ConfluenceTestImportEntry> = entries
            .iter()
            .filter_map(|e| serde_json::from_value::<ConfluenceTestImportEntry>(e.clone()).ok())
            .collect();
        let tables = Self::generate_single_table(&import_entries);
        let existing = Self::count_existing_entries(&content);
        Ok(ConfluencePreviewResult {
            current_title: title,
            current_version: version,
            generated_tables: tables,
            entry_count: import_entries.len() as u32,
            existing_entry_count: existing as u32,
        })
    }

    /// Sync entries into a Confluence page: strip prior generated markers,
    /// append fresh tables, and update the page (bumping its version).
    pub async fn sync_to_confluence(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        payload: &SyncToConfluencePayload,
    ) -> Result<SyncToConfluenceResult> {
        let (title, mut content, version) = self.get_page_preview(config, page_id).await?;
        content = Self::strip_generated_markers(&content);

        let import_entries: Vec<ConfluenceTestImportEntry> = payload
            .entries
            .iter()
            .filter_map(|e| serde_json::from_value::<ConfluenceTestImportEntry>(e.clone()).ok())
            .collect();
        let entry_count = import_entries.len() as u32;
        let tables = Self::generate_single_table(&import_entries);

        let mut new_content = String::new();
        new_content.push_str("<h1>QA Test Cases</h1>");
        new_content.push_str("<ac:structured-macro ac:name=\"toc\"/>");
        new_content.push_str(&tables);
        new_content.push_str("\n<p>Generated by QA Buddy</p>");
        content.push_str(&new_content);

        let updated = self.update_page(config, page_id, &title, &content, version).await?;
        let page_url = updated
            .get("_links")
            .and_then(|l| l.get("base"))
            .and_then(|b| b.as_str())
            .map(|b| format!("{}{}", normalize_url(b), format!("/pages/viewpage.action?pageId={page_id}")))
            .unwrap_or_else(|| format!("/pages/viewpage.action?pageId={page_id}"));

        Ok(SyncToConfluenceResult {
            page_title: title,
            page_url,
            entry_count,
            image_count: 0,
            attachment_count: 0,
        })
    }

    /// Parse a Confluence page's storage body into import entries. Each
    /// `<table>` whose first row has header cells is treated as a set of test
    /// rows; columns are mapped to ConfluenceTestImportEntry fields by header.
    pub async fn parse_confluence_entries(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        _options: &ParseConfluenceEntriesOptions,
    ) -> Result<ParseConfluenceEntriesResult> {
        let (title, content, _version) = match self.get_page_preview(config, page_id).await {
            Ok(t) => (Some(t.0), t.1, t.2),
            Err(e) => {
                return Ok(ParseConfluenceEntriesResult {
                    page_id: page_id.to_string(),
                    page_title: String::new(),
                    content_loaded: false,
                    entries: vec![],
                    jira_server_id: None,
                    error: Some(e.to_string()),
                    debug: None,
                });
            }
        };
        let entries = parse_tables_to_entries(&content);
        let jira_server_id = self.client(config).detect_jira_server_id().await;

        Ok(ParseConfluenceEntriesResult {
            page_id: page_id.to_string(),
            page_title: title.unwrap_or_default(),
            content_loaded: true,
            entries,
            jira_server_id,
            error: None,
            debug: None,
        })
    }
}

// ── free helpers ────────────────────────────────────────────────────────

/// Minimal HTML-escape for cell values pushed into storage format.
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Parse every `<table>` in a storage body into import entries, mapping
/// columns by header text (TestCase No, Function Name, Scenario, Steps,
/// Expected Result). Falls back to positional columns when headers are absent.
fn parse_tables_to_entries(content: &str) -> Vec<ConfluenceTestImportEntry> {
    let mut entries: Vec<ConfluenceTestImportEntry> = Vec::new();
    let table_re = regex::Regex::new(r"(?is)<table\b[^>]*>([\s\S]*?)</table>").unwrap();
    let mut counter = 1usize;
    for table_cap in table_re.captures_iter(content) {
        let body = &table_cap[1];
        let (header_map, has_header) = parse_header_map(body);
        let row_re = regex::Regex::new(r"(?is)<tr\b[^>]*>([\s\S]*?)</tr>").unwrap();
        let cell_re = regex::Regex::new(r"(?is)<t[dh][^>]*>([\s\S]*?)</t[dh]>").unwrap();
        for row_cap in row_re.captures_iter(body) {
            let row = &row_cap[1];
            // Skip header rows.
            if regex::Regex::new(r"(?i)<th\b").unwrap().is_match(row) {
                continue;
            }
            let cells: Vec<String> = cell_re
                .captures_iter(row)
                .map(|c| strip_inner_tags(&c[1]).trim().to_string())
                .collect();
            if cells.iter().all(|c| c.is_empty()) {
                continue;
            }
            let entry = build_entry(&cells, &header_map, has_header, &mut counter);
            entries.push(entry);
        }
    }
    entries
}

/// Map header text → column index. Returns (map, has_header).
fn parse_header_map(body: &str) -> (std::collections::HashMap<String, usize>, bool) {
    let mut map = std::collections::HashMap::new();
    let row_re = regex::Regex::new(r"(?is)<tr\b[^>]*>([\s\S]*?)</tr>").unwrap();
    let cell_re = regex::Regex::new(r"(?is)<th\b[^>]*>([\s\S]*?)</th>").unwrap();
    for row_cap in row_re.captures_iter(body) {
        let headers: Vec<String> = cell_re
            .captures_iter(&row_cap[1])
            .map(|c| normalise_header(&c[1]))
            .collect();
        if !headers.is_empty() {
            for (i, h) in headers.iter().enumerate() {
                map.insert(h.clone(), i);
            }
            return (map, true);
        }
    }
    (map, false)
}

fn normalise_header(raw: &str) -> String {
    let s = strip_inner_tags(raw).trim().to_lowercase();
    s.replace("test case no", "testcase")
        .replace("testcase no", "testcase")
        .replace("function name", "function")
        .replace("scenario", "scenario")
        .replace("steps", "steps")
        .replace("test steps", "steps")
        .replace("expected result", "expected")
        .replace("expected", "expected")
}

fn build_entry(
    cells: &[String],
    header_map: &std::collections::HashMap<String, usize>,
    has_header: bool,
    counter: &mut usize,
) -> ConfluenceTestImportEntry {
    let pick = |key: &str| -> String {
        header_map
            .get(key)
            .and_then(|i| cells.get(*i))
            .cloned()
            .unwrap_or_default()
    };
    let (test_case_no, function_name, scenario, steps, expected_result) = if has_header {
        (
            pick("testcase"),
            pick("function"),
            pick("scenario"),
            pick("steps"),
            pick("expected"),
        )
    } else {
        // Positional fallback: [No, Function, Scenario, Steps, Expected].
        (
            cells.first().cloned().unwrap_or_default(),
            cells.get(1).cloned().unwrap_or_default(),
            cells.get(2).cloned().unwrap_or_default(),
            cells.get(3).cloned().unwrap_or_default(),
            cells.get(4).cloned().unwrap_or_default(),
        )
    };
    let id = format!("tc-{}", counter);
    *counter += 1;
    ConfluenceTestImportEntry {
        id,
        issue_key: String::new(),
        scenario,
        steps,
        expected_result,
        function_name,
        test_case_no,
        input_data: String::new(),
        selected: true,
    }
}

/// Remove nested HTML tags inside a cell, collapse whitespace.
fn strip_inner_tags(raw: &str) -> String {
    let re = regex::Regex::new(r"(?is)<[^>]+>").unwrap();
    let ws = regex::Regex::new(r"\s+").unwrap();
    let decoded = raw
        .replace("&nbsp;", " ")
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'");
    let stripped = re.replace_all(&decoded, " ");
    ws.replace_all(stripped.trim(), " ").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_tables_to_entries_positional() {
        let html = r#"<table><tbody>
            <tr><th>TestCase No</th><th>Function Name</th><th>Scenario</th><th>Steps</th><th>Expected Result</th></tr>
            <tr><td>TC-001</td><td>Login</td><td>User logs in</td><td>Click login</td><td>Dashboard shown</td></tr>
        </tbody></table>"#;
        let entries = parse_tables_to_entries(html);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].test_case_no, "TC-001");
        assert_eq!(entries[0].function_name, "Login");
        assert_eq!(entries[0].expected_result, "Dashboard shown");
    }

    #[test]
    fn generate_single_table_roundtrip() {
        let entries = vec![ConfluenceTestImportEntry {
            id: "tc-1".into(),
            issue_key: String::new(),
            scenario: "Login".into(),
            steps: "Click".into(),
            expected_result: "OK".into(),
            function_name: "Auth".into(),
            test_case_no: "TC-1".into(),
            input_data: String::new(),
            selected: true,
        }];
        let table = ConfluenceService::generate_single_table(&entries);
        assert!(table.contains("TC-1"));
        assert!(table.contains("Auth"));
    }

    #[test]
    fn strip_generated_markers_removes_gen_paragraph() {
        let html = "<p>hello</p>\n<p>Generated by QA Buddy — 2026-06-18</p>\n<p>world</p>";
        let cleaned = ConfluenceService::strip_generated_markers(html);
        assert!(!cleaned.contains("Generated by QA Buddy"));
        assert!(cleaned.contains("hello"));
        assert!(cleaned.contains("world"));
    }
}
