//! Confluence service — held in app state. P3 wires connection testing + page
//! access; this module (P5b) adds page preview, attachment upload, page update,
//! Jira server-id detection, table generation, and Confluence-entry parsing.
//!
//! The HTML storage-format manipulation (XHTML tables, TOC macros, generated
//! markers) mirrors the Electron `confluence-service.ts` + `table-formatter.ts`
//! behaviour, ported to Rust regex.

use base64::Engine as _;
use serde_json::Value;

use crate::models::app_config::ConfluenceConfig;
use crate::models::jira::ConfluenceTestImportEntry;
use crate::models::misc::{
    ConfluenceParseProgress, ParseConfluenceEntriesOptions, ParseConfluenceEntriesResult,
    SyncToConfluencePayload, SyncToConfluenceResult,
};
use crate::services::confluence::client::ConfluenceClient;
use crate::services::error::Result;
use crate::services::http::normalize_url;
use tauri::{AppHandle, Emitter};

pub struct ConfluenceService;

impl ConfluenceService {
    pub fn new() -> Self {
        Self
    }

    fn client(&self, config: &ConfluenceConfig) -> ConfluenceClient {
        ConfluenceClient::new(config)
    }

    /// Probe Confluence connectivity; returns a status string.
    pub async fn test_connection(&self, config: &ConfluenceConfig) -> Result<String> {
        self.client(config).validate_connection().await
    }

    /// Fetch a raw Confluence page document.
    pub async fn get_page(&self, config: &ConfluenceConfig, page_id: &str) -> Result<Value> {
        self.client(config).get_page(page_id).await
    }

    /// Resolve a user-facing Confluence URL to a page document.
    pub async fn get_page_by_url(&self, config: &ConfluenceConfig, url: &str) -> Result<Value> {
        self.client(config).get_page_by_url(url).await
    }

    /// List pages for a space key or ancestor/page id. Used by RAG indexing.
    pub async fn list_pages(&self, config: &ConfluenceConfig, space_or_page_id: &str) -> Result<Vec<Value>> {
        self.client(config).list_pages(space_or_page_id).await
    }

    pub async fn get_attachments(&self, config: &ConfluenceConfig, page_id: &str) -> Result<Vec<Value>> {
        self.client(config).get_attachments(page_id).await
    }

    pub async fn download_attachment(&self, config: &ConfluenceConfig, download_path: &str) -> Result<Vec<u8>> {
        self.client(config).download_attachment(download_path).await
    }

    /// Lightweight page preview: title, storage body, version.
    pub async fn get_page_preview(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
    ) -> Result<(String, String, u32)> {
        let page = self.get_page(config, page_id).await?;
        let title = page["title"].as_str().unwrap_or("").to_string();
        let content = page["body"]["storage"]["value"]
            .as_str()
            .unwrap_or("")
            .to_string();
        let version = page["version"]["number"].as_u64().unwrap_or(1) as u32;
        Ok((title, content, version))
    }

    /// Resolve the Jira application-link server id from Confluence applinks.
    pub async fn detect_jira_server_id(&self, config: &ConfluenceConfig) -> Result<Option<String>> {
        Ok(self.client(config).detect_jira_server_id().await)
    }

    pub async fn upload_attachment(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        filename: &str,
        data: Vec<u8>,
    ) -> Result<Value> {
        self.client(config)
            .upload_attachment(page_id, filename, data)
            .await
    }

    pub async fn update_page(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        title: &str,
        content: &str,
        version: u32,
    ) -> Result<Value> {
        self.client(config)
            .update_page(page_id, title, content, version)
            .await
    }

    fn emit_parse_progress(
        app_handle: Option<&AppHandle>,
        stage: &str,
        message: impl Into<String>,
        current: usize,
        total: usize,
        detail: Option<String>,
    ) {
        if let Some(handle) = app_handle {
            let _ = handle.emit(
                "confluence-parse-progress",
                ConfluenceParseProgress {
                    stage: stage.to_string(),
                    message: message.into(),
                    current,
                    total,
                    detail,
                },
            );
        }
    }

    // ── Storage-format helpers ──────────────────────────────────────────

    /// Strip only our own "Generated by QA Buddy" trailer markers.
    /// Does NOT touch TOC macros, h1, or any other page content — those belong
    /// to the page owner and must be preserved exactly as fetched.
    fn strip_generated_markers(content: &str) -> String {
        let gen = regex::Regex::new(
            r#"(?i)\s*<p>\s*Generated by QA Buddy\s*[-—]\s*[^<]+</p>\s*"#,
        )
        .unwrap();
        let gen_simple = regex::Regex::new(
            r#"(?i)\s*<p>\s*Generated by QA Buddy\s*</p>\s*"#,
        )
        .unwrap();
        let mut out = gen.replace_all(content, "").to_string();
        out = gen_simple.replace_all(&out, "").to_string();
        out
    }

    /// Map category value from QA Buddy to Confluence display label.
    fn category_label(category: &str) -> &'static str {
        match category.trim().to_uppercase().as_str() {
            "TC_REGRESSION" | "REGRESSION" | "REGRESI" => "Regresi",
            "TC_UNHAPPY" | "UNHAPPY" | "NEGATIVE" => "Negative",
            "TC_HAPPY" | "HAPPY" | "POSITIVE" => "Positive",
            _ => "Positive",
        }
    }

    /// Build the HTML for a single Result cell — plain text, no colour.
    fn result_cell_html(result: &str) -> String {
        let label = match result.trim().to_uppercase().as_str() {
            "PASS" | "PASSED" => "Passed",
            "FAIL" | "FAILED" => "Failed",
            other if other.is_empty() => "",
            _ => result.trim(),
        };
        if label.is_empty() {
            String::new()
        } else {
            format!("<p>{}</p>", escape_html(label))
        }
    }

    /// Build the Screen Capture cell HTML: one Expand macro containing all images.
    fn screen_capture_cell_html(
        entry_id: &str,
        images: &[serde_json::Value],
        uploaded: &std::collections::HashMap<(String, String), String>,
    ) -> String {
        let mut sorted = images.to_vec();
        sorted.sort_by_key(|img| img["order"].as_u64().unwrap_or(0));

        // Group images by expandGroup, preserving insertion order of groups.
        let mut group_order: Vec<String> = Vec::new();
        let mut groups: std::collections::HashMap<String, Vec<&serde_json::Value>> =
            std::collections::HashMap::new();
        for img in &sorted {
            let group = img["expandGroup"].as_str().unwrap_or("").trim().to_string();
            if !groups.contains_key(&group) {
                group_order.push(group.clone());
            }
            groups.entry(group).or_default().push(img);
        }

        let mut all_expands = String::new();
        for group_key in &group_order {
            let imgs = &groups[group_key];
            let expand_title = if group_key.is_empty() {
                "Click here to expand...".to_string()
            } else {
                escape_html(group_key)
            };

            let mut inner = String::new();
            for img in imgs.iter() {
                let orig_name = img["name"].as_str().unwrap_or("").to_string();
                let note = img["note"].as_str().unwrap_or("").trim().to_string();
                let key = (entry_id.to_string(), orig_name);
                if let Some(uploaded_name) = uploaded.get(&key) {
                    if !note.is_empty() {
                        inner.push_str(&format!(
                            r#"<p><strong>{}</strong></p>"#,
                            escape_html(&note)
                        ));
                    }
                    inner.push_str(&format!(
                        r#"<p><ac:image ac:width="450"><ri:attachment ri:filename="{}" /></ac:image></p>"#,
                        escape_html(uploaded_name)
                    ));
                }
            }

            if !inner.is_empty() {
                all_expands.push_str(&format!(
                    r#"<ac:structured-macro ac:name="expand"><ac:parameter ac:name="title">{}</ac:parameter><ac:rich-text-body>{}</ac:rich-text-body></ac:structured-macro>"#,
                    expand_title, inner
                ));
            }
        }

        all_expands
    }

    /// Update existing vertical-card tables in `content` in-place.
    ///
    /// Strategy: scan for every `<table>…</table>` block; if it is a vertical
    /// table whose "No. Test Case" row value matches one of the payload entries,
    /// replace the value cells for all known fields with the new data.
    /// Returns the mutated content and a set of entry IDs that were matched.
    fn patch_existing_tables(
        content: &str,
        entries: &[serde_json::Value],
        uploaded: &std::collections::HashMap<(String, String), String>,
        jira_server_id: Option<&str>,
    ) -> (String, std::collections::HashSet<String>) {
        // Build lookup by sourceTableIndex → entry (primary, matches parse order).
        let mut by_source: std::collections::HashMap<usize, &serde_json::Value> =
            std::collections::HashMap::new();
        for entry in entries {
            if let Some(idx) = entry["sourceTableIndex"].as_u64() {
                by_source.insert(idx as usize, entry);
            }
        }

        // Build lookup: composite key (testCaseNo + "|" + functionName) → entry
        // (fallback for entries without sourceTableIndex, e.g. manually added).
        let mut by_tc: std::collections::HashMap<String, &serde_json::Value> =
            std::collections::HashMap::new();
        for entry in entries {
            let tc  = entry["testCaseNo"].as_str().unwrap_or("").trim().to_lowercase();
            let fun = entry["functionName"].as_str().unwrap_or("").trim().to_lowercase();
            if !tc.is_empty() {
                // Primary key: tc + function (exact match across sub-sections)
                by_tc.insert(format!("{tc}|{fun}"), entry);
                // Fallback key: tc alone (used only if no function match found — see below)
                by_tc.entry(tc).or_insert(entry);
            }
        }

        let mut matched_ids: std::collections::HashSet<String> = std::collections::HashSet::new();

        // Collect all table positions first, then build result in one forward pass
        // so we never need offset tracking (which breaks when replacements shrink content).
        let table_positions = iter_table_positions(content);

        // For each table position, decide what to emit: original or patched
        struct Patch { tbl_start: usize, tbl_end: usize, replacement: String, entry_id: String }
        let mut patches: Vec<Patch> = Vec::new();

        // Mirrors the parse step: only vertical-card tables get a sourceTableIndex.
        let mut vertical_index = 0usize;

        for (tbl_start, tbl_end) in table_positions {
            let original_table = &content[tbl_start..tbl_end];

            if !is_vertical_table(original_table) {
                continue;
            }
            // Only tables the parser would count as import entries advance the index.
            let mut dummy = 0usize;
            if parse_vertical_table(original_table, &mut dummy).is_none() {
                continue;
            }
            let my_index = vertical_index;
            vertical_index += 1;

            // Prefer the exact sourceTableIndex match (updates the same table in place).
            let entry = by_source.get(&my_index).copied();
            let entry = match entry {
                Some(e) => Some(e),
                None => {
                    let tc_val = extract_vertical_cell(original_table, "no. test case")
                        .or_else(|| extract_vertical_cell(original_table, "no test case"))
                        .or_else(|| extract_vertical_cell(original_table, "no. tc"))
                        .unwrap_or_default();
                    let tc_key = tc_val.trim().to_lowercase();
                    if tc_key.is_empty() { continue; }

                    let fun_val = extract_vertical_cell(original_table, "function")
                        .or_else(|| extract_vertical_cell(original_table, "function name"))
                        .unwrap_or_default();
                    let fun_key = fun_val.trim().to_lowercase();

                    // Try composite key first; fall back to tc-only if function not present
                    let composite = format!("{tc_key}|{fun_key}");
                    if let Some(e) = by_tc.get(&composite) {
                        Some(*e)
                    } else if !fun_key.is_empty() {
                        // No composite match — this table belongs to a different sub-section
                        None
                    } else if let Some(e) = by_tc.get(&tc_key) {
                        Some(*e)
                    } else {
                        None
                    }
                }
            };
            let Some(entry) = entry else { continue };

            let entry_id = entry["id"].as_str().unwrap_or("").to_string();
            let images = entry["images"].as_array().cloned().unwrap_or_default();

            let category_html = format!("<p>{}</p>", escape_html(Self::category_label(entry["category"].as_str().unwrap_or(""))));
            let replacements: Vec<(&str, String)> = vec![
                ("function",        format!("<p>{}</p>", escape_html(entry["functionName"].as_str().unwrap_or("")))),
                ("scenario",        scenario_to_html(entry["scenario"].as_str().unwrap_or(""), jira_server_id)),
                ("kategori",        category_html.clone()),
                ("category",        category_html),
                ("input data",      text_to_list_html(entry["inputData"].as_str().unwrap_or(""))),
                ("steps",           text_to_list_html(entry["steps"].as_str().unwrap_or(""))),
                ("expected result", text_to_list_html(entry["expectedResult"].as_str().unwrap_or(""))),
                ("result",          Self::result_cell_html(entry["result"].as_str().unwrap_or(""))),
                ("screen capture",  Self::screen_capture_cell_html(&entry_id, &images, uploaded)),
            ];

            let mut new_table = original_table.to_string();
            for (label, new_value) in &replacements {
                new_table = replace_vertical_cell_value(&new_table, label, new_value);
            }

            if new_table != original_table {
                patches.push(Patch { tbl_start, tbl_end, replacement: new_table, entry_id });
            }
        }

        // Build the final string in a single forward pass over the original content
        let mut result = String::with_capacity(content.len() + 1024);
        let mut cursor = 0usize;
        for patch in &patches {
            result.push_str(&content[cursor..patch.tbl_start]);
            result.push_str(&patch.replacement);
            cursor = patch.tbl_end;
            matched_ids.insert(patch.entry_id.clone());
        }
        result.push_str(&content[cursor..]);

        (result, matched_ids)
    }

    /// Generate vertical-card XHTML tables for entries that had no match in
    /// the existing page content (append-only path).
    pub fn generate_vertical_tables(
        entries: &[serde_json::Value],
        uploaded: &std::collections::HashMap<(String, String), String>,
        jira_server_id: Option<&str>,
    ) -> String {
        let mut html = String::new();
        for entry in entries {
            let id            = entry["id"].as_str().unwrap_or("").to_string();
            let test_case_no  = entry["testCaseNo"].as_str().unwrap_or("").to_string();
            let function_name = entry["functionName"].as_str().unwrap_or("").to_string();
            let scenario      = entry["scenario"].as_str().unwrap_or("").to_string();
            let category      = Self::category_label(entry["category"].as_str().unwrap_or(""));
            let input_data    = entry["inputData"].as_str().unwrap_or("").to_string();
            let steps         = entry["steps"].as_str().unwrap_or("").to_string();
            let expected      = entry["expectedResult"].as_str().unwrap_or("").to_string();
            let result        = entry["result"].as_str().unwrap_or("").to_string();
            let images        = entry["images"].as_array().cloned().unwrap_or_default();

            let screen_capture_html = Self::screen_capture_cell_html(&id, &images, uploaded);
            let result_html         = Self::result_cell_html(&result);
            let scenario_html       = scenario_to_html(&scenario, jira_server_id);

            html.push_str(r#"<table class="wrapped confluenceTable"><colgroup><col style="width: 200px;"/><col/></colgroup><tbody>"#);
            html.push_str(&format!("<tr><th class=\"confluenceTh\">No. Test Case</th><td class=\"confluenceTd\"><p>{}</p></td></tr>", escape_html(&test_case_no)));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Function</th><td class=\"confluenceTd\"><p>{}</p></td></tr>", escape_html(&function_name)));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Scenario</th><td class=\"confluenceTd\">{scenario_html}</td></tr>"));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Kategori</th><td class=\"confluenceTd\"><p>{}</p></td></tr>", escape_html(category)));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Input Data</th><td class=\"confluenceTd\">{}</td></tr>", text_to_list_html(&input_data)));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Steps</th><td class=\"confluenceTd\">{}</td></tr>", text_to_list_html(&steps)));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Expected Result</th><td class=\"confluenceTd\">{}</td></tr>", text_to_list_html(&expected)));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Result</th><td class=\"confluenceTd\">{}</td></tr>", result_html));
            html.push_str(&format!("<tr><th class=\"confluenceTh\">Screen Capture</th><td class=\"confluenceTd\">{}</td></tr>", screen_capture_html));
            html.push_str("</tbody></table><p>&nbsp;</p>");
        }
        html
    }

    /// Generate a single XHTML `<table>` from import entries (one row each).
    /// Columns: TestCase No | Function Name | Scenario | Steps | Expected Result.
    /// Kept for parse roundtrip tests only — sync now uses generate_vertical_tables.
    pub fn generate_single_table(entries: &[ConfluenceTestImportEntry]) -> String {
        let mut html = String::from(
            "<table class=\"wrapped confluenceTable\"><colgroup><col/><col/><col/><col/><col/></colgroup>",
        );
        html.push_str("<tbody>");
        html.push_str(
            "<tr><th class=\"confluenceTh\">TestCase No</th><th class=\"confluenceTh\">Function Name</th><th class=\"confluenceTh\">Scenario</th><th class=\"confluenceTh\">Steps</th><th class=\"confluenceTh\">Expected Result</th></tr>",
        );
        for entry in entries {
            html.push_str(&format!(
                "<tr><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td><td class=\"confluenceTd\">{}</td></tr>",
                escape_html(&entry.test_case_no),
                escape_html(&entry.function_name),
                escape_html(&entry.scenario),
                escape_html(&entry.steps),
                escape_html(&entry.expected_result),
            ));
        }
        html.push_str("</tbody></table>");
        html
    }

    // ── High-level operations ───────────────────────────────────────────

    /// Sync entries into a Confluence page.
    ///
    /// If the page already has vertical-card tables whose "No. Test Case" value
    /// matches a payload entry, those tables are updated **in-place** (no new
    /// table is created).  Entries with no matching table are appended at the end.
    /// Images are uploaded as attachments and referenced in a single Expand macro.
    pub async fn sync_to_confluence(
        &self,
        config: &ConfluenceConfig,
        page_id: &str,
        payload: &SyncToConfluencePayload,
    ) -> Result<SyncToConfluenceResult> {
        let (title, raw_content, version) = self.get_page_preview(config, page_id).await?;
        let content = sanitize_confluence_storage_html(&raw_content);

        let entry_count = payload.entries.len() as u32;

        // ── 1. Check existing attachments to skip redundant uploads ──────
        let existing_attachments = self.get_attachments(config, page_id).await.unwrap_or_default();
        let existing_filenames: std::collections::HashSet<String> = existing_attachments
            .iter()
            .filter_map(|a| a["title"].as_str().map(|s| s.to_string()))
            .collect();

        // ── 2. Collect image upload tasks ────────────────────────────────
        let mut uploaded: std::collections::HashMap<(String, String), String> =
            std::collections::HashMap::new();
        let mut total_images = 0u32;

        struct UploadTaskItem {
            entry_id: String,
            orig_name: String,
            upload_name: String,
            bytes: Vec<u8>,
        }

        let mut tasks_to_upload: Vec<UploadTaskItem> = Vec::new();

        for entry in &payload.entries {
            let entry_id = entry["id"].as_str().unwrap_or("").to_string();
            let images = entry["images"].as_array().cloned().unwrap_or_default();
            let mut sorted = images.clone();
            sorted.sort_by_key(|img| img["order"].as_u64().unwrap_or(0));

            for img in &sorted {
                let orig_name = img["name"].as_str().unwrap_or("attachment.png").to_string();
                if orig_name.is_empty() {
                    continue;
                }
                let data_uri = img["data"].as_str().unwrap_or("");

                // If an attachment with this exact name already lives on the
                // page, reuse it instead of re-uploading. After a parse the image
                // name IS the Confluence attachment title, so unchanged
                // attachments (only steps/expected edited) are never re-sent.
                if existing_filenames.contains(&orig_name) {
                    uploaded.insert((entry_id.clone(), orig_name.clone()), orig_name);
                    continue;
                }

                // Nothing to upload and nothing to reference.
                if data_uri.is_empty() {
                    continue;
                }

                let base64_data = if let Some(pos) = data_uri.find(',') {
                    &data_uri[pos + 1..]
                } else {
                    data_uri
                };
                let bytes = match base64::engine::general_purpose::STANDARD.decode(base64_data) {
                    Ok(b) => b,
                    Err(_) => continue,
                };

                let safe_entry = entry_id.replace(['/', '\\', ' '], "_");
                let upload_name = format!("{safe_entry}_{orig_name}");
                tasks_to_upload.push(UploadTaskItem {
                    entry_id: entry_id.clone(),
                    orig_name,
                    upload_name,
                    bytes,
                });
            }
        }

        // Run uploads concurrently (max 8 at a time)
        if !tasks_to_upload.is_empty() {
            let client = self.client(config);
            let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(8));
            let mut join_set = tokio::task::JoinSet::new();
            let page_id_str = page_id.to_string();

            for item in tasks_to_upload {
                let client = client.clone();
                let sem = sem.clone();
                let page_id_clone = page_id_str.clone();

                join_set.spawn(async move {
                    let _permit = sem.acquire().await;
                    let res = client
                        .upload_attachment(&page_id_clone, &item.upload_name, item.bytes)
                        .await;
                    (item.entry_id, item.orig_name, item.upload_name, res.is_ok())
                });
            }

            while let Some(res) = join_set.join_next().await {
                if let Ok((entry_id, orig_name, upload_name, success)) = res {
                    if success {
                        uploaded.insert((entry_id, orig_name), upload_name);
                        total_images += 1;
                    }
                }
            }
        }

        // ── 3. Patch existing tables in-place ────────────────────────────
        let jira_server_id = config.jira_server_id.as_deref();
        let (mut content, matched_ids) =
            Self::patch_existing_tables(&content, &payload.entries, &uploaded, jira_server_id);

        // ── 4. Append tables for entries not found in existing content ───
        let new_entries: Vec<&serde_json::Value> = payload
            .entries
            .iter()
            .filter(|e| {
                let id = e["id"].as_str().unwrap_or("");
                !matched_ids.contains(id)
            })
            .collect();

        if !new_entries.is_empty() {
            // Remove the "Generated by QA Buddy" trailer if present so we append before it
            content = Self::strip_generated_markers(&content);
            let jira_server_id = config.jira_server_id.as_deref();
            let new_tables = Self::generate_vertical_tables(
                &new_entries.into_iter().cloned().collect::<Vec<_>>(),
                &uploaded,
                jira_server_id,
            );
            content.push_str(&new_tables);
        }

        // ── 5. Repair any unclosed inline tags left over from the original page ─
        let content = close_unclosed_inline_tags(&content);

        // ── 6. Write back to Confluence ──────────────────────────────────
        let updated = self.update_page(config, page_id, &title, &content, version).await?;
        let page_url = updated
            .get("_links")
            .and_then(|l| l.get("base"))
            .and_then(|b| b.as_str())
            .map(|b| format!(
                "{}/pages/viewpage.action?pageId={page_id}",
                normalize_url(b)
            ))
            .unwrap_or_else(|| format!("/pages/viewpage.action?pageId={page_id}"));

        Ok(SyncToConfluenceResult {
            page_title: title,
            page_url,
            entry_count,
            image_count: total_images,
            attachment_count: total_images,
        })
    }

    /// Parse a Confluence page's storage body into import entries. Each
    /// `<table>` whose first row has header cells is treated as a set of test
    /// rows; columns are mapped to ConfluenceTestImportEntry fields by header.
    pub async fn parse_confluence_entries(
        &self,
        app_handle: Option<&AppHandle>,
        config: &ConfluenceConfig,
        page_id: &str,
        options: &ParseConfluenceEntriesOptions,
    ) -> Result<ParseConfluenceEntriesResult> {
        Self::emit_parse_progress(
            app_handle,
            "fetch_page",
            "Memuat halaman Confluence",
            0,
            1,
            Some(format!("Page ID: {page_id}")),
        );
        let (title, content, _version) = match self.get_page_preview(config, page_id).await {
            Ok(t) => (Some(t.0), t.1, t.2),
            Err(e) => {
                Self::emit_parse_progress(
                    app_handle,
                    "error",
                    "Gagal memuat halaman Confluence",
                    0,
                    1,
                    Some(e.to_string()),
                );
                return Ok(ParseConfluenceEntriesResult {
                    page_id: page_id.to_string(),
                    page_title: String::new(),
                    content_loaded: false,
                    entries: vec![],
                    jira_server_id: None,
                    error: Some(e.to_string()),
                    debug: None,
                });
            }
        };
        Self::emit_parse_progress(
            app_handle,
            "fetch_page",
            "Halaman Confluence berhasil dimuat",
            1,
            1,
            title.clone(),
        );
        let table_positions = iter_table_positions(&content);
        let total_tables = table_positions.len();
        Self::emit_parse_progress(
            app_handle,
            "parse_tables",
            "Mulai parsing tabel",
            0,
            total_tables,
            Some(format!("{total_tables} tabel terdeteksi")),
        );
        let mut entries = parse_tables_to_entries_with_progress(&content, Some(&table_positions), |current, total| {
            Self::emit_parse_progress(
                app_handle,
                "parse_tables",
                format!("Parsing tabel {current} / {total}"),
                current,
                total,
                None,
            );
        });
        let jira_server_id = if options.include_jira_server_id {
            Self::emit_parse_progress(
                app_handle,
                "detect_jira",
                "Mendeteksi Jira Server ID",
                0,
                1,
                None,
            );
            let detected = self.client(config).detect_jira_server_id().await;
            Self::emit_parse_progress(
                app_handle,
                "detect_jira",
                "Deteksi Jira Server ID selesai",
                1,
                1,
                detected.clone(),
            );
            detected
        } else {
            None
        };

        // Download screen capture attachments concurrently for entries that need them
        let needs_images = options.include_images && entries.iter().any(|e| !e.screen_capture_filenames.is_empty());
        if needs_images {
            Self::emit_parse_progress(
                app_handle,
                "fetch_attachments",
                "Memuat attachment page",
                0,
                1,
                None,
            );
            // Fetch all page attachments once
            let all_attachments = self.get_attachments(config, page_id).await.unwrap_or_default();
            Self::emit_parse_progress(
                app_handle,
                "fetch_attachments",
                "Attachment page berhasil dimuat",
                1,
                1,
                Some(format!("{} attachment ditemukan", all_attachments.len())),
            );
            // Build filename → download_path map
            let att_map: std::collections::HashMap<String, String> = all_attachments
                .iter()
                .filter_map(|a| {
                    let name = a["title"].as_str()?.to_string();
                    let path = a["_links"]["download"].as_str()?.to_string();
                    Some((name, path))
                })
                .collect();

            struct DownloadTaskItem {
                entry_idx: usize,
                order: usize,
                filename: String,
                download_path: String,
            }

            let mut download_tasks: Vec<DownloadTaskItem> = Vec::new();
            for (entry_idx, entry) in entries.iter().enumerate() {
                for (order, filename) in entry.screen_capture_filenames.iter().enumerate() {
                    if let Some(download_path) = att_map.get(filename) {
                        download_tasks.push(DownloadTaskItem {
                            entry_idx,
                            order,
                            filename: filename.clone(),
                            download_path: download_path.clone(),
                        });
                    }
                }
            }

            if !download_tasks.is_empty() {
                let total_downloads = download_tasks.len();
                Self::emit_parse_progress(
                    app_handle,
                    "download_images",
                    "Mulai memproses image attachment",
                    0,
                    total_downloads,
                    None,
                );
                let client = self.client(config);
                let sem = std::sync::Arc::new(tokio::sync::Semaphore::new(8));
                let mut join_set = tokio::task::JoinSet::new();

                for item in download_tasks {
                    let client = client.clone();
                    let sem = sem.clone();

                    join_set.spawn(async move {
                        let _permit = sem.acquire().await;
                        let res = client.download_attachment(&item.download_path).await;
                        (item.entry_idx, item.order, item.filename, res)
                    });
                }

                let mut downloaded_map: std::collections::HashMap<
                    usize,
                    Vec<(usize, crate::models::jira::ConfluenceEntryImage)>,
                > = std::collections::HashMap::new();
                let mut processed = 0usize;

                while let Some(res) = join_set.join_next().await {
                    processed += 1;
                    Self::emit_parse_progress(
                        app_handle,
                        "download_images",
                        format!("Memproses image {processed} / {total_downloads}"),
                        processed,
                        total_downloads,
                        None,
                    );
                    if let Ok((entry_idx, order, filename, Ok(bytes))) = res {
                        let ext = filename.rsplit('.').next().unwrap_or("png").to_lowercase();
                        let mime = match ext.as_str() {
                            "jpg" | "jpeg" => "image/jpeg",
                            "gif" => "image/gif",
                            "webp" => "image/webp",
                            _ => "image/png",
                        };
                        let b64 = base64_encode(&bytes);
                        let img = crate::models::jira::ConfluenceEntryImage {
                            id: uuid::Uuid::new_v4().to_string(),
                            name: filename,
                            data: format!("data:{mime};base64,{b64}"),
                            order: order + 1,
                            note: String::new(),
                            expand_group: String::new(),
                        };
                        downloaded_map.entry(entry_idx).or_default().push((order, img));
                    }
                }

                for (entry_idx, mut list) in downloaded_map {
                    list.sort_by_key(|(order, _)| *order);
                    entries[entry_idx].images = list.into_iter().map(|(_, img)| img).collect();
                }
            }
        }

        Self::emit_parse_progress(
            app_handle,
            "done",
            format!("Selesai: {} entries ditemukan", entries.len()),
            entries.len(),
            entries.len(),
            title.clone(),
        );

        Ok(ParseConfluenceEntriesResult {
            page_id: page_id.to_string(),
            page_title: title.unwrap_or_default(),
            content_loaded: true,
            entries,
            jira_server_id,
            error: None,
            debug: None,
        })
    }
}

// ── free helpers ────────────────────────────────────────────────────────

fn base64_encode(data: &[u8]) -> String {
    base64::engine::general_purpose::STANDARD.encode(data)
}

fn parse_tables_to_entries_with_progress<F: FnMut(usize, usize)>(
    content: &str,
    table_positions: Option<&[(usize, usize)]>,
    mut on_progress: F,
) -> Vec<ConfluenceTestImportEntry> {
    let mut entries: Vec<ConfluenceTestImportEntry> = Vec::new();
    let table_positions = table_positions
        .map(|positions| positions.to_vec())
        .unwrap_or_else(|| iter_table_positions(content));
    let total = table_positions.len();
    let row_re = RE_ROW.get_or_init(|| regex::Regex::new(r"(?is)<tr\b[^>]*>([\s\S]*?)</tr>").unwrap());
    let cell_re = RE_CELL.get_or_init(|| regex::Regex::new(r"(?is)<t[dh][^>]*>([\s\S]*?)</t[dh]>").unwrap());
    let th_re = RE_TH.get_or_init(|| regex::Regex::new(r"(?i)<th\b").unwrap());

    let mut counter = 1usize;
    let mut vertical_index = 0usize;
    for (idx, (start, end)) in table_positions.iter().enumerate() {
        let body = &content[*start..*end];
        on_progress(idx + 1, total);

        if is_vertical_table(body) {
            if let Some(mut entry) = parse_vertical_table(body, &mut counter) {
                entry.source_table_index = Some(vertical_index);
                vertical_index += 1;
                entries.push(entry);
            }
            continue;
        }

        let (header_map, has_header) = parse_header_map(body);
        for row_cap in row_re.captures_iter(body) {
            let row = &row_cap[1];
            if th_re.is_match(row) {
                continue;
            }
            let cells: Vec<String> = cell_re
                .captures_iter(row)
                .map(|c| c[1].to_string())
                .collect();
            if cells.iter().all(|c| strip_inner_tags(c).trim().is_empty()) {
                continue;
            }
            let entry = build_entry(&cells, &header_map, has_header, &mut counter);
            entries.push(entry);
        }
    }

    entries
}

/// Extract the plain-text value of a named field row in a vertical-card table.
/// Exact case-insensitive match on the trimmed label text.
fn extract_vertical_cell(table_html: &str, field: &str) -> Option<String> {
    for (_rs, _re, inner_start, inner_end) in iter_tr_positions(table_html) {
        let row_inner = &table_html[inner_start..inner_end];
        let cells = split_row_cells(row_inner);
        if cells.len() < 2 { continue; }
        let label = strip_inner_tags(&cells[0]).trim().to_lowercase();
        if label == field {
            return Some(strip_inner_tags(&cells[1]).trim().to_string());
        }
    }
    None
}

/// Replace the value cell (second `<td>`) of a named field row in a vertical-card table.
/// Exact case-insensitive match on the trimmed label text of the first cell.
///
/// Uses depth-tracking iterators (not naive regex) so nested tables and AC macros
/// that contain `</tr>` or `</td>` inside them are handled correctly.
fn replace_vertical_cell_value(table_html: &str, field: &str, new_value: &str) -> String {
    for (_row_start, _row_end, row_inner_start, row_inner_end)
        in iter_tr_positions(table_html)
    {
        let row_inner = &table_html[row_inner_start..row_inner_end];
        let cells = split_row_cells(row_inner);
        if cells.len() < 2 { continue; }

        let label = strip_inner_tags(&cells[0]).trim().to_lowercase();
        if label != field { continue; }

        // Found the right row — now splice the new value into the second cell.
        if let Some((cell_open, inner_start, inner_end, cell_end))
            = find_second_cell_positions(row_inner)
        {
            // cell positions are all relative to row_inner
            let open_tag  = &row_inner[cell_open..inner_start];
            let close_tag = &row_inner[inner_end..cell_end];
            let new_row_inner = format!(
                "{}{}{}{}{}",
                &row_inner[..cell_open],
                open_tag,
                new_value,
                close_tag,
                &row_inner[cell_end..],
            );
            let mut result = table_html.to_string();
            result.replace_range(row_inner_start..row_inner_end, &new_row_inner);
            return result;
        }
        break; // found the row but cell parse failed — leave unchanged
    }

    table_html.to_string()
}

/// Iterate top-level `<table>…</table>` blocks in `html` using depth tracking,
/// yielding `(start, end)` byte positions. Nested tables (inside macros or cells)
/// are skipped — only the outermost `<table>` boundaries are returned.
fn iter_table_positions(html: &str) -> Vec<(usize, usize)> {
    let open_re  = regex::Regex::new(r"(?i)<table\b[^>]*>").unwrap();
    let close_re = regex::Regex::new(r"(?i)</table>").unwrap();
    let len = html.len();
    let mut results = Vec::new();
    let mut pos = 0usize;

    while pos < len {
        let Some(open_m) = open_re.find(&html[pos..]) else { break };
        let tbl_start = pos + open_m.start();
        let mut depth = 1i32;
        let mut cur = pos + open_m.end();

        while cur < len && depth > 0 {
            let rest = &html[cur..];
            let next_open  = open_re.find(rest).map(|m| m.start());
            let next_close = close_re.find(rest).map(|m| (m.start(), m.end()));
            match (next_open, next_close) {
                (Some(o), Some((c, _))) if o < c => {
                    depth += 1;
                    cur += open_re.find(rest).unwrap().end();
                }
                (_, Some((_, ce))) => {
                    depth -= 1;
                    cur += ce;
                    if depth == 0 {
                        results.push((tbl_start, cur));
                        pos = cur;
                        break;
                    }
                }
                _ => { pos = len; break; }
            }
        }
        if depth > 0 { break; }
    }
    results
}

/// Iterate `<tr>…</tr>` blocks in `html`, yielding
/// `(row_start, row_end, inner_start, inner_end)` where the inner span
/// does **not** include the opening `<tr…>` or closing `</tr>` tag.
/// Depth-tracks nested `<tr>` so that tables-within-tables are handled
/// (Confluence Expand macros can embed arbitrary content).
fn iter_tr_positions(html: &str) -> Vec<(usize, usize, usize, usize)> {
    let open_re  = regex::Regex::new(r"(?i)<tr\b[^>]*>").unwrap();
    let close_re = regex::Regex::new(r"(?i)</tr>").unwrap();
    let len = html.len();
    let mut results = Vec::new();
    let mut pos = 0usize;

    while pos < len {
        let Some(open_m) = open_re.find(&html[pos..]) else { break };
        let tr_start      = pos + open_m.start();
        let inner_start   = pos + open_m.end();
        let mut depth = 1i32;
        let mut cur = inner_start;

        while cur < len && depth > 0 {
            let rest = &html[cur..];
            let next_open  = open_re.find(rest).map(|m| m.start());
            let next_close = close_re.find(rest).map(|m| m.start());
            match (next_open, next_close) {
                (Some(o), Some(c)) if o < c => {
                    depth += 1;
                    cur += open_re.find(rest).unwrap().end();
                }
                (_, Some(c)) => {
                    depth -= 1;
                    let close_end = cur + close_re.find(rest).unwrap().end();
                    if depth == 0 {
                        results.push((tr_start, close_end, inner_start, cur + c));
                        cur = close_end;
                        pos = cur;
                        break;
                    }
                    cur = close_end;
                }
                _ => { pos = len; break; }
            }
        }
        if depth > 0 { break; }
    }
    results
}

/// Within a row's inner HTML find the second `<t[dh]…>…</t[dh]>` cell using
/// depth-tracking, and return `(cell_open_start, inner_start, inner_end, cell_end)`.
/// All positions are relative to `row_inner`.
fn find_second_cell_positions(row_inner: &str) -> Option<(usize, usize, usize, usize)> {
    let open_re  = regex::Regex::new(r"(?i)<t[dh]\b[^>]*>").unwrap();
    let close_re = regex::Regex::new(r"(?i)</t[dh]>").unwrap();
    let len = row_inner.len();
    let mut cell_idx = 0usize;
    let mut pos = 0usize;

    while pos < len {
        let Some(open_m) = open_re.find(&row_inner[pos..]) else { break };
        let cell_open_start = pos + open_m.start();
        let inner_start     = pos + open_m.end();
        let mut depth = 1i32;
        let mut cur = inner_start;

        while cur < len && depth > 0 {
            let rest = &row_inner[cur..];
            let next_open  = open_re.find(rest).map(|m| m.start());
            let next_close = close_re.find(rest).map(|m| m.start());
            match (next_open, next_close) {
                (Some(o), Some(c)) if o < c => {
                    depth += 1;
                    cur += open_re.find(rest).unwrap().end();
                }
                (_, Some(c)) => {
                    depth -= 1;
                    let close_end = cur + close_re.find(rest).unwrap().end();
                    if depth == 0 {
                        cell_idx += 1;
                        if cell_idx == 2 {
                            return Some((cell_open_start, inner_start, cur + c, close_end));
                        }
                        pos = close_end;
                        break;
                    }
                    cur = close_end;
                }
                _ => return None,
            }
        }
        if depth > 0 { break; }
    }
    None
}

/// Sanitize existing Confluence page content so that every `<td>`/`<th>` whose
/// content starts with bare inline elements (`<strong>`, `<span>`, `<em>`, `<a>`,
/// `<code>`, etc.) — i.e. NOT already wrapped in a block-level element — gets
/// the whole cell content wrapped in a `<p>…</p>`.
///
/// This is needed because old content (created before our XHTML fix) may have
/// cells like `<td><strong>PASS</strong></td>` which Confluence rejects when we
/// write the page back.
fn sanitize_td_inline_content(html: &str) -> String {
    // Inline-only tags that need wrapping when they appear at the top of a cell
    let inline_tag_re = regex::Regex::new(
        r"(?i)^<(strong|em|span|a|code|s|u|sub|sup|b|i)\b"
    ).unwrap();
    // Block-level tags — if the content starts with one of these, no wrapping needed
    let block_tag_re = regex::Regex::new(
        r"(?i)^<(p|ol|ul|li|h[1-6]|table|tbody|tr|th|td|div|ac:|ri:|blockquote|pre)\b"
    ).unwrap();

    let open_re  = regex::Regex::new(r"(?i)<t[dh]\b[^>]*>").unwrap();
    let close_re = regex::Regex::new(r"(?i)</t[dh]>").unwrap();
    let len = html.len();
    let mut result = String::with_capacity(html.len() + 256);
    let mut pos = 0usize;

    while pos < len {
        let Some(open_m) = open_re.find(&html[pos..]) else {
            result.push_str(&html[pos..]);
            break;
        };
        // Copy everything up to and including the opening tag
        let _open_abs_start = pos + open_m.start();
        let open_abs_end    = pos + open_m.end();
        result.push_str(&html[pos..open_abs_end]);

        // Depth-track to find the matching close tag
        let inner_start = open_abs_end;
        let mut depth = 1i32;
        let mut cur = inner_start;
        let mut inner_end = inner_start;
        let mut cell_end = inner_start;

        while cur < len && depth > 0 {
            let rest = &html[cur..];
            let next_open  = open_re.find(rest).map(|m| m.start());
            let next_close = close_re.find(rest).map(|m| (m.start(), m.end()));
            match (next_open, next_close) {
                (Some(o), Some((c, _))) if o < c => {
                    depth += 1;
                    cur += open_re.find(rest).unwrap().end();
                }
                (_, Some((c, ce))) => {
                    depth -= 1;
                    if depth == 0 {
                        inner_end = cur + c;
                        cell_end  = cur + ce;
                        break;
                    }
                    cur += ce;
                }
                _ => { break; }
            }
        }

        if depth > 0 {
            // Unclosed cell — just copy the rest as-is
            result.push_str(&html[open_abs_end..]);
            break;
        }

        let inner = &html[inner_start..inner_end];
        let close_tag = &html[inner_end..cell_end];
        let trimmed = inner.trim();

        let needs_wrap = if trimmed.is_empty() {
            false
        } else if trimmed.starts_with('<') {
            // Starts with a tag — inline if matched by inline_tag_re, needs wrap
            // Block if matched by block_tag_re, no wrap needed
            inline_tag_re.is_match(trimmed) && !block_tag_re.is_match(trimmed)
        } else {
            // Starts with plain text — always needs a <p> wrapper
            true
        };

        if needs_wrap {
            result.push_str("<p>");
            result.push_str(trimmed);
            result.push_str("</p>");
        } else {
            result.push_str(inner);
        }
        result.push_str(close_tag);
        pos = cell_end;
    }

    result
}

/// Sanitize Confluence storage-format HTML fetched from an existing page so that
/// the content can be safely written back via the REST API without a 400 error.
///
/// Problems this handles:
/// 1. Unknown / non-Confluence XML tags (`<xml>`, `<o:p>`, `<w:...>`, `<v:...>`,
///    `<m:...>`, `<x:...>`, etc.) left over from pasted Office/Word content —
///    strip the tag itself but keep the inner text.
/// 2. Orphan close tags (`</div>`, `</xml>`, `</span>` etc.) that have no
///    matching open tag — remove them.
/// 3. Unclosed inline tags (`<strong>`, `<em>`, …) at block boundaries —
///    handled by `close_unclosed_inline_tags` which is called after this.
fn sanitize_confluence_storage_html(html: &str) -> String {
    // ── Step 1: strip Office/Word XML namespace tags entirely (open + close) ──
    // These are tags like <xml>, <o:p>, <w:sdtPr>, <v:shape>, <m:math> etc.
    // We remove the tag but keep any text content inside.
    // Also remove XML processing instructions: <?xml ...?> and <!...>
    let office_tag_re = regex::Regex::new(
        r"(?i)</?(?:xml|o:[a-z0-9]+|w:[a-z0-9]+|v:[a-z0-9]+|m:[a-z0-9]+|x:[a-z0-9]+)[^>]*/?>"
    ).unwrap();
    let pi_re = regex::Regex::new(r"(?i)<\?xml[^?]*\?>|<![A-Za-z][^>]*>").unwrap();
    let mut out = office_tag_re.replace_all(html, "").to_string();
    out = pi_re.replace_all(&out, "").to_string();

    // ── Step 2: track open/close counts for block-level tags and remove
    //    orphan close tags (close tags with no matching open tag) ──────────
    // We only track the tags that Confluence commonly complains about.
    const BLOCK_TAGS: &[&str] = &["div", "section", "article", "header", "footer", "nav", "aside"];
    out = remove_orphan_close_tags(&out, BLOCK_TAGS);

    out
}

/// Remove close tags (e.g. `</div>`) that have no corresponding open tag.
/// Uses a running depth counter: whenever a close tag is encountered with
/// depth == 0 (no matching open tag seen yet), that close tag is dropped.
fn remove_orphan_close_tags(html: &str, tags: &[&str]) -> String {
    let mut out = html.to_string();
    for tag in tags {
        let open_re  = regex::Regex::new(&format!(r"(?i)<{tag}\b[^>]*>")).unwrap();
        let close_re = regex::Regex::new(&format!(r"(?i)</{tag}>")).unwrap();

        // Build sorted event list: (pos, end, is_close)
        let mut events: Vec<(usize, usize, bool)> = Vec::new();
        for m in open_re.find_iter(&out)  { events.push((m.start(), m.end(), false)); }
        for m in close_re.find_iter(&out) { events.push((m.start(), m.end(), true));  }
        events.sort_by_key(|e| e.0);

        // Walk events; collect positions of orphan close tags to remove
        let mut depth = 0i32;
        let mut orphans: Vec<(usize, usize)> = Vec::new();
        for (pos, end, is_close) in &events {
            if *is_close {
                if depth == 0 {
                    orphans.push((*pos, *end));
                } else {
                    depth -= 1;
                }
            } else {
                depth += 1;
            }
        }

        if orphans.is_empty() { continue; }

        // Rebuild string skipping orphan ranges
        let mut result = String::with_capacity(out.len());
        let mut cursor = 0usize;
        for (start, end) in &orphans {
            result.push_str(&out[cursor..*start]);
            cursor = *end;
        }
        result.push_str(&out[cursor..]);
        out = result;
    }
    out
}

/// Remove orphan close tags for both block and inline tags.
/// An orphan close tag is one with no matching open tag before it in the document.
fn close_unclosed_inline_tags(html: &str) -> String {
    // Remove orphan close tags for all tags that Confluence's XHTML parser enforces.
    // Order matters: process outer tags before inner ones.
    const TAGS: &[&str] = &[
        "div", "section",
        "p",
        "strong", "em", "span", "b", "i", "s", "u", "code",
    ];
    remove_orphan_close_tags(html, TAGS)
}

/// Minimal HTML-escape for cell values pushed into storage format.
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Convert scenario text to Confluence HTML.
/// Any Jira issue URL (https://.../browse/KEY-123) is turned into a Jira macro.
/// Non-URL text on other lines is emitted as a plain <p>.
fn scenario_to_html(scenario: &str, jira_server_id: Option<&str>) -> String {
    let url_re = regex::Regex::new(r"https?://[^\s]+/browse/([A-Z][A-Z0-9_]+-\d+)").unwrap();
    let mut html = String::new();
    for line in scenario.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() { continue; }
        if let Some(cap) = url_re.captures(trimmed) {
            let issue_key = &cap[1];
            let server_id = jira_server_id.unwrap_or("jira");
            html.push_str(&format!(
                r#"<p><ac:structured-macro ac:name="jira"><ac:parameter ac:name="server">System JIRA</ac:parameter><ac:parameter ac:name="serverId">{server_id}</ac:parameter><ac:parameter ac:name="key">{issue_key}</ac:parameter></ac:structured-macro></p>"#,
            ));
        } else {
            html.push_str(&format!("<p>{}</p>", escape_html(trimmed)));
        }
    }
    if html.is_empty() {
        html.push_str(&format!("<p>{}</p>", escape_html(scenario)));
    }
    html
}

/// Convert steps/expected-result text into a Confluence XHTML list.
/// Mirrors the Electron `toListItems(text, format, plainLinesAsBullets=true)`:
///   - all lines numbered ("1. " / "1) ") → `<ol>`
///   - all lines bulleted ("- " / "* " / "• ") → `<ul>`
///   - otherwise (plain lines) → `<ul>` with each line as a bullet
fn text_to_list_html(text: &str) -> String {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return String::new();
    }

    // Split into non-empty lines.
    let lines: Vec<&str> = trimmed.lines().map(|s| s.trim()).filter(|s| !s.is_empty()).collect();

    let numbered_re = regex::Regex::new(r"^\d+[.)]\s+").unwrap();
    let bullet_re   = regex::Regex::new(r"^[-*•]\s+").unwrap();

    let is_numbered = lines.iter().all(|l| numbered_re.is_match(l));
    let is_bullet   = lines.iter().all(|l| bullet_re.is_match(l));

    if is_numbered {
        let mut html = String::from("<ol>");
        for line in &lines {
            let content = numbered_re.replace(line, "");
            html.push_str(&format!("<li>{}</li>", escape_html(content.trim())));
        }
        html.push_str("</ol>");
        return html;
    }

    if is_bullet {
        let mut html = String::from("<ul>");
        for line in &lines {
            let content = bullet_re.replace(line, "");
            html.push_str(&format!("<li>{}</li>", escape_html(content.trim())));
        }
        html.push_str("</ul>");
        return html;
    }

    // Legacy inline format: "- 1. foo - 2. bar" (single line with separators).
    let inline_re = regex::Regex::new(r"(?:^|\s)-\s*\d+\.\s*").unwrap();
    let parts: Vec<&str> = inline_re.split(trimmed).map(|s| s.trim()).filter(|s| !s.is_empty()).collect();
    if parts.len() > 1 {
        let mut html = String::from("<ol>");
        for part in &parts {
            html.push_str(&format!("<li>{}</li>", escape_html(part)));
        }
        html.push_str("</ol>");
        return html;
    }

    // Plain lines — render each as a bullet (main branch's plainLinesAsBullets=true).
    let mut html = String::from("<ul>");
    for line in &lines {
        html.push_str(&format!("<li>{}</li>", escape_html(line)));
    }
    html.push_str("</ul>");
    html
}

/// Normalize a field label from a vertical-format table row (left column).
fn normalise_field_label(raw: &str) -> String {
    strip_inner_tags(raw).trim().to_lowercase()
}

/// Detect whether a table uses the vertical (card) format used by Documentation Sync,
/// where each row is: | Field Label | Value | and field labels match known QA fields.
fn is_vertical_table(body: &str) -> bool {
    let row_re = regex::Regex::new(r"(?is)<tr\b[^>]*>([\s\S]*?)</tr>").unwrap();
    let cell_re = regex::Regex::new(r"(?is)<t[dh][^>]*>([\s\S]*?)</t[dh]>").unwrap();
    let known: &[&str] = &[
        "no. test case", "no test case", "no. tc", "function", "scenario",
        "kategori", "input data", "steps", "test steps", "expected result",
        "result", "screen capture",
    ];
    let mut matched = 0usize;
    let mut checked = 0usize;
    for row_cap in row_re.captures_iter(body) {
        let cells: Vec<String> = cell_re
            .captures_iter(&row_cap[1])
            .map(|c| normalise_field_label(&c[1]))
            .collect();
        if cells.len() >= 1 {
            checked += 1;
            let label = cells[0].as_str();
            if known.iter().any(|k| label.contains(k)) {
                matched += 1;
            }
        }
        if checked >= 6 {
            break;
        }
    }
    checked > 0 && matched >= 3
}

/// Extract scenario text from a Confluence cell, mirroring the Electron
/// `extractTextValue` + `cleanConfluenceMacros`: each Jira macro is replaced by
/// its issue key while surrounding summary text is preserved.
/// e.g. `<p>Login <ac:structured-macro jira key="TRALOS-1"/>…</p>` → `Login TRALOS-1`.
fn extract_scenario_text(raw: &str) -> String {
    // Replace full <ac:structured-macro ac:name="jira">…</ac:structured-macro>
    // blocks with their issue key (keeps surrounding text).
    let macro_re = regex::Regex::new(
        r#"(?is)<ac:structured-macro\b[^>]*\bac:name\s*=\s*"jira"[^>]*>.*?</ac:structured-macro>"#,
    )
    .unwrap();
    let key_re = regex::Regex::new(
        r#"(?is)<ac:parameter\b[^>]*\bac:name\s*=\s*"key"[^>]*>([\s\S]*?)</ac:parameter>"#,
    )
    .unwrap();
    let cleaned = macro_re.replace_all(raw, |caps: &regex::Captures| {
        let keys: Vec<String> = key_re
            .captures_iter(&caps[0])
            .map(|c| strip_inner_tags(&c[1]).trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
        if keys.is_empty() {
            String::new()
        } else {
            keys.join(", ")
        }
    });
    let text = strip_inner_tags(&cleaned);
    if text.trim().is_empty() {
        // No jira macro found — plain text fallback.
        strip_inner_tags(raw).trim().to_string()
    } else {
        text.trim().to_string()
    }
}

/// Extract attachment filenames from a Confluence cell.
/// Handles both direct <ri:attachment ri:filename="..."/> and
/// filenames wrapped inside Expand macros or other nested structures.
/// Also handles single-quoted attribute values.
fn extract_attachment_filenames(raw: &str) -> Vec<String> {
    // Match ri:filename with double or single quotes
    let re = regex::Regex::new(
        r#"(?i)<ri:attachment\b[^>]*\bri:filename\s*=\s*(?:"([^"]+)"|'([^']+)')"#,
    )
    .unwrap();
    re.captures_iter(raw)
        .map(|c| {
            c.get(1)
                .or_else(|| c.get(2))
                .map(|m| m.as_str().to_string())
                .unwrap_or_default()
        })
        .filter(|s| !s.is_empty())
        .collect()
}

/// Split a table row's raw HTML into individual cell raw HTML contents.
/// Uses a simple open/close counter to handle nested tags inside cells.
fn split_row_cells(row_html: &str) -> Vec<String> {
    let mut cells = Vec::new();
    let open_re = regex::Regex::new(r"(?i)<(td|th)\b[^>]*>").unwrap();
    let close_re = regex::Regex::new(r"(?i)</(td|th)>").unwrap();
    let len = row_html.len();
    let mut pos = 0usize;

    while pos < len {
        let Some(open_cap) = open_re.find(&row_html[pos..]) else { break };
        let cell_start = pos + open_cap.end();
        let mut depth = 1i32;
        let mut cur = cell_start;
        while cur < len && depth > 0 {
            let rest = &row_html[cur..];
            let next_open = open_re.find(rest).map(|m| m.start());
            let next_close = close_re.find(rest).map(|m| m.start());
            match (next_open, next_close) {
                (Some(o), Some(c)) if o < c => {
                    depth += 1;
                    cur += open_re.find(rest).unwrap().end();
                }
                (_, Some(c)) => {
                    depth -= 1;
                    let close_end = cur + close_re.find(rest).unwrap().end();
                    if depth == 0 {
                        cells.push(row_html[cell_start..cur + c].to_string());
                        cur = close_end;
                        break;
                    }
                    cur = close_end;
                }
                _ => break,
            }
        }
        if cur <= cell_start { break; }
        pos = cur;
    }
    cells
}

/// Find the position of "Screen Capture" label row in the table body,
/// then extract ALL ri:attachment filenames from the rest of the table body
/// after that label — this handles Expand macros that contain </tr> inside them.
fn extract_screen_capture_filenames_from_body(body: &str) -> Vec<String> {
    // Find where the Screen Capture label appears (case-insensitive plain text)
    let lower = body.to_lowercase();
    let marker_pos = lower
        .find("screen capture")
        .or_else(|| lower.find("screenshot"))
        .or_else(|| lower.find("screen shot"));

    if let Some(pos) = marker_pos {
        // Search for ri:attachment anywhere after the marker in the full body
        extract_attachment_filenames(&body[pos..])
    } else {
        Vec::new()
    }
}

/// Parse a vertical-format table (one test case per table block).
/// Rows: | Field Label | Value |
fn parse_vertical_table(body: &str, counter: &mut usize) -> Option<ConfluenceTestImportEntry> {
    let mut test_case_no = String::new();
    let mut function_name = String::new();
    let mut scenario = String::new();
    let mut steps = String::new();
    let mut expected_result = String::new();
    let mut input_data = String::new();
    let mut found_any = false;

    for (_rs, _re, inner_start, inner_end) in iter_tr_positions(body) {
        let row_inner = &body[inner_start..inner_end];
        // Use depth-aware cell splitter to handle nested tags inside cells
        let raw_cells = split_row_cells(row_inner);
        if raw_cells.len() < 2 {
            continue;
        }
        let label = strip_inner_tags(&raw_cells[0]).trim().to_lowercase();
        let raw_value = &raw_cells[1];

        if label.contains("no. test case") || label.contains("no test case") || label.contains("no. tc") || label == "no tc" {
            test_case_no = strip_inner_tags(raw_value).trim().to_string();
            found_any = true;
        } else if label.contains("function") {
            function_name = strip_inner_tags(raw_value).trim().to_string();
            found_any = true;
        } else if label.contains("scenario") {
            scenario = extract_scenario_text(raw_value);
            found_any = true;
        } else if label.contains("input data") {
            input_data = extract_text_lines(raw_value);
            found_any = true;
        } else if label.contains("steps") || label.contains("langkah") {
            steps = extract_text_lines(raw_value);
            found_any = true;
        } else if label.contains("expected") || label.contains("hasil yang diharapkan") {
            expected_result = extract_text_lines(raw_value);
            found_any = true;
        }
    }

    // Extract screen capture filenames from the full table body (bypasses lazy </tr> truncation)
    // This correctly handles Expand macros that embed </tr> inside their body.
    let screen_capture_filenames = extract_screen_capture_filenames_from_body(body);

    if !found_any {
        return None;
    }

    let id = format!("tc-{}", counter);
    *counter += 1;
    Some(ConfluenceTestImportEntry {
        id,
        issue_key: String::new(),
        test_case_no,
        function_name,
        scenario,
        input_data,
        steps,
        expected_result,
        selected: true,
        source_table_index: None,
        screen_capture_filenames,
        images: Vec::new(), // populated later by parse_confluence_entries
    })
}

static RE_TABLE: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
static RE_ROW: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
static RE_CELL: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
static RE_TH: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
static RE_TH_CELL: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();

/// Parse every `<table>` in a storage body into import entries.
/// Supports two formats:
///   1. Horizontal: first row = headers (No. Test Case, Function, Scenario, Steps, Expected Result)
///   2. Vertical (card): each row = | Field Label | Value | — one test case per table
fn parse_tables_to_entries(content: &str) -> Vec<ConfluenceTestImportEntry> {
    parse_tables_to_entries_with_progress(content, None, |_current, _total| {})
}

/// Map header text → column index. Returns (map, has_header).
fn parse_header_map(body: &str) -> (std::collections::HashMap<String, usize>, bool) {
    let mut map = std::collections::HashMap::new();
    let row_re = RE_ROW.get_or_init(|| regex::Regex::new(r"(?is)<tr\b[^>]*>([\s\S]*?)</tr>").unwrap());
    let th_cell_re = RE_TH_CELL.get_or_init(|| regex::Regex::new(r"(?is)<th\b[^>]*>([\s\S]*?)</th>").unwrap());
    for row_cap in row_re.captures_iter(body) {
        let headers: Vec<String> = th_cell_re
            .captures_iter(&row_cap[1])
            .map(|c| normalise_header(&c[1]))
            .collect();
        if !headers.is_empty() {
            for (i, h) in headers.iter().enumerate() {
                map.insert(h.clone(), i);
            }
            return (map, true);
        }
    }
    (map, false)
}

fn normalise_header(raw: &str) -> String {
    let s = strip_inner_tags(raw).trim().to_lowercase();
    s.replace("test case no", "testcase")
        .replace("testcase no", "testcase")
        .replace("function name", "function")
        .replace("scenario", "scenario")
        .replace("steps", "steps")
        .replace("test steps", "steps")
        .replace("expected result", "expected")
        .replace("expected", "expected")
}

fn build_entry(
    cells: &[String],
    header_map: &std::collections::HashMap<String, usize>,
    has_header: bool,
    counter: &mut usize,
) -> ConfluenceTestImportEntry {
    let pick_raw = |key: &str| -> Option<&str> {
        header_map
            .get(key)
            .and_then(|i| cells.get(*i))
            .map(|s| s.as_str())
    };
    let (test_case_no, function_name, scenario, steps, expected_result) = if has_header {
        (
            pick_raw("testcase").map(|v| strip_inner_tags(v).trim().to_string()).unwrap_or_default(),
            pick_raw("function").map(|v| strip_inner_tags(v).trim().to_string()).unwrap_or_default(),
            pick_raw("scenario").map(extract_scenario_text).unwrap_or_default(),
            pick_raw("steps").map(extract_text_lines).unwrap_or_default(),
            pick_raw("expected").map(extract_text_lines).unwrap_or_default(),
        )
    } else {
        // Positional fallback: [No, Function, Scenario, Steps, Expected].
        (
            cells.first().map(|v| strip_inner_tags(v).trim().to_string()).unwrap_or_default(),
            cells.get(1).map(|v| strip_inner_tags(v).trim().to_string()).unwrap_or_default(),
            cells.get(2).map(|v| extract_scenario_text(v)).unwrap_or_default(),
            cells.get(3).map(|v| extract_text_lines(v)).unwrap_or_default(),
            cells.get(4).map(|v| extract_text_lines(v)).unwrap_or_default(),
        )
    };
    let id = format!("tc-{}", counter);
    *counter += 1;
    ConfluenceTestImportEntry {
        id,
        issue_key: String::new(),
        scenario,
        steps,
        expected_result,
        function_name,
        test_case_no,
        input_data: String::new(),
        selected: true,
        source_table_index: None,
        screen_capture_filenames: Vec::new(),
        images: Vec::new(),
    }
}

/// Remove nested HTML tags inside a cell, collapse whitespace.
fn strip_inner_tags(raw: &str) -> String {
    let re = regex::Regex::new(r"(?is)<[^>]+>").unwrap();
    let ws = regex::Regex::new(r"\s+").unwrap();
    let decoded = raw
        .replace("&nbsp;", " ")
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'");
    let stripped = re.replace_all(&decoded, " ");
    ws.replace_all(stripped.trim(), " ").to_string()
}

/// Extract list/paragraph content from a Confluence cell into newline-separated
/// lines. Mirrors the Electron `extractTextLines` (confluence-service.ts):
///   1. `<li>` items joined with `\n`
///   2. `<p>` items joined with `\n` (each paragraph split on `<br>` so
///      "a<br>b" becomes two lines, not one)
///   3. `<br>`-separated segments joined with `\n`
///   4. otherwise the single plain-text value
fn extract_text_lines(raw: &str) -> String {
    let li_re = regex::Regex::new(r"(?is)<li\b[^>]*>([\s\S]*?)</li>").unwrap();
    let li_items: Vec<String> = li_re
        .captures_iter(raw)
        .map(|c| strip_inner_tags(&c[1]).trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    if !li_items.is_empty() {
        return li_items.join("\n");
    }

    let p_re = regex::Regex::new(r"(?is)<p\b[^>]*>([\s\S]*?)</p>").unwrap();
    let p_items: Vec<String> = p_re
        .captures_iter(raw)
        .flat_map(|c| split_br_lines(&c[1]))
        .filter(|s| !s.is_empty())
        .collect();
    if !p_items.is_empty() {
        return p_items.join("\n");
    }

    let br_items: Vec<String> = split_br_lines(raw);
    if br_items.len() > 1 {
        return br_items.join("\n");
    }

    strip_inner_tags(raw).trim().to_string()
}

/// Split inner HTML on `<br>` (any variant) and strip tags from each segment.
fn split_br_lines(inner: &str) -> Vec<String> {
    let br_re = regex::Regex::new(r"(?i)<br\s*/?>").unwrap();
    br_re
        .split(inner)
        .map(|s| strip_inner_tags(s).trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_tables_to_entries_positional() {
        let html = r#"<table><tbody>
            <tr><th>TestCase No</th><th>Function Name</th><th>Scenario</th><th>Steps</th><th>Expected Result</th></tr>
            <tr><td>TC-001</td><td>Login</td><td>User logs in</td><td>Click login</td><td>Dashboard shown</td></tr>
        </tbody></table>"#;
        let entries = parse_tables_to_entries(html);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].test_case_no, "TC-001");
        assert_eq!(entries[0].function_name, "Login");
        assert_eq!(entries[0].expected_result, "Dashboard shown");
    }

    #[test]
    fn generate_single_table_roundtrip() {
        let entries = vec![ConfluenceTestImportEntry {
            id: "tc-1".into(),
            issue_key: String::new(),
            scenario: "Login".into(),
            steps: "Click".into(),
            expected_result: "OK".into(),
            function_name: "Auth".into(),
            test_case_no: "TC-1".into(),
            input_data: String::new(),
            selected: true,
            source_table_index: None,
            screen_capture_filenames: Vec::new(),
            images: Vec::new(),
        }];
        let table = ConfluenceService::generate_single_table(&entries);
        assert!(table.contains("TC-1"));
        assert!(table.contains("Auth"));
    }

    #[test]
    fn strip_generated_markers_removes_gen_paragraph() {
        let html = "<p>hello</p>\n<p>Generated by QA Buddy — 2026-06-18</p>\n<p>world</p>";
        let cleaned = ConfluenceService::strip_generated_markers(html);
        assert!(!cleaned.contains("Generated by QA Buddy"));
        assert!(cleaned.contains("hello"));
        assert!(cleaned.contains("world"));
    }

    #[test]
    fn extract_text_lines_splits_br_inside_p() {
        let html = r#"<td class="confluenceTd"><p>Reguler: 4687400237774496<br>Co-Branding: 4359720100296005<br>Corporate: 5534790146445614</p></td>"#;
        let lines = extract_text_lines(html);
        let expected = "Reguler: 4687400237774496\nCo-Branding: 4359720100296005\nCorporate: 5534790146445614";
        assert_eq!(lines, expected);
    }

    #[test]
    fn extract_text_lines_joins_list_items() {
        let html = "<ol><li>Klik menu</li><li>Pilih opsi</li></ol>";
        let lines = extract_text_lines(html);
        assert_eq!(lines, "Klik menu\nPilih opsi");
    }
}
